import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { AccessContext, discoverWorkspaces, getAccessContext, getStaffProfile, getWorkspaces, hasStoredSession, SchoolWorkspace, signIn, signOut, StaffProfile, switchWorkspace } from '@/lib/auth-client';

const features = [
  { label: 'My school', permission: 'Schools.View', entitlement: 'school-administration' },
  { label: 'Classes', permission: 'Academics.View', entitlement: 'academic-structure' },
  { label: 'Staff directory', permission: 'Staff.View', entitlement: 'staff-management' },
  { label: 'Students', permission: 'Students.View', entitlement: 'student-information' },
];

export default function StaffHome() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(true);
  const [message, setMessage] = useState('Restoring your secure session…'); const [access, setAccess] = useState<AccessContext | null>(null);
  const [workspaces, setWorkspaces] = useState<SchoolWorkspace[]>([]); const [profile, setProfile] = useState<StaffProfile | null>(null);

  async function loadWorkspace() { const nextAccess = await getAccessContext(); if (!nextAccess.audiences.some(value => value === 'Teacher' || value === 'Staff')) throw new Error('This account does not have staff access.'); const [nextWorkspaces, linkedProfile] = await Promise.all([getWorkspaces(), getStaffProfile()]); if (!linkedProfile) throw new Error('No active staff record is securely linked to this account in the selected school.'); setAccess(nextAccess); setWorkspaces(nextWorkspaces); setProfile(linkedProfile); }
  useEffect(() => { void (async () => { try { if (await hasStoredSession()) { await loadWorkspace(); setMessage('Your secure session was restored.'); } else setMessage('Sign in with your staff account.'); } catch (error) { await signOut(); setMessage(error instanceof Error ? error.message : 'Your session could not be restored.'); } finally { setBusy(false); } })(); }, []);
  async function login() { setBusy(true); try { const available = await discoverWorkspaces(email, password); const first = available[0]; if (!first) throw new Error('No active school membership is linked to this account.'); await signIn(email, password, first.tenantId, first.campuses[0]?.campusId); await loadWorkspace(); setPassword(''); setMessage('Connected with server-verified staff and school links.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Sign-in failed.'); } finally { setBusy(false); } }
  async function changeSchool(workspace: SchoolWorkspace) { setBusy(true); try { await switchWorkspace(workspace.tenantId, workspace.campuses[0]?.campusId); await loadWorkspace(); setMessage(`Switched securely to ${workspace.tenantName}.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'School switching failed.'); } finally { setBusy(false); } }
  async function logout() { await signOut(); setAccess(null); setWorkspaces([]); setProfile(null); setPassword(''); setMessage('You have signed out securely.'); }

  const availableFeatures = features.filter(feature => access?.permissions.includes(feature.permission) && access.entitlements[feature.entitlement]?.enabled);
  return <ThemedView style={styles.screen}><SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><ThemedText type="title">Staff workspace</ThemedText><ThemedText>Your tools, securely scoped to your school, role, and campus.</ThemedText></View>{busy && !access ? <ActivityIndicator /> : !access ? <View style={styles.card}><TextInput autoCapitalize="none" keyboardType="email-address" placeholder="Email" value={email} onChangeText={setEmail} style={styles.input} /><TextInput placeholder="Password" secureTextEntry value={password} onChangeText={setPassword} style={styles.input} /><Pressable disabled={busy || !email || !password} onPress={() => void login()} style={styles.button}>{busy ? <ActivityIndicator color="#fff" /> : <ThemedText style={styles.buttonText}>Find my schools and sign in</ThemedText>}</Pressable></View> : <><View style={styles.card}><ThemedText type="subtitle">School workspace</ThemedText>{workspaces.map(workspace => <Pressable key={workspace.tenantId} disabled={busy || workspace.tenantId === access.tenantId} onPress={() => void changeSchool(workspace)} style={[styles.choice, workspace.tenantId === access.tenantId && styles.selected]}><ThemedText type="smallBold">{workspace.tenantName}</ThemedText><ThemedText type="small">{workspace.tenantId === access.tenantId ? 'Current school' : 'Switch school'}</ThemedText></Pressable>)}</View><View style={styles.card}><ThemedText type="subtitle">Verified staff profile</ThemedText>{profile && <View style={styles.tile}><ThemedText type="smallBold">{profile.firstName} {profile.lastName}</ThemedText><ThemedText type="small">{profile.staffNumber} · {profile.category}</ThemedText><ThemedText type="small">{profile.campusName}{profile.positionName ? ` · ${profile.positionName}` : ''}</ThemedText></View>}</View><View style={styles.card}><ThemedText type="subtitle">Available tools</ThemedText>{availableFeatures.length ? availableFeatures.map(feature => <View key={feature.label} style={styles.tile}><ThemedText type="smallBold">{feature.label}</ThemedText><ThemedText type="small">Available for your permissions and school plan</ThemedText></View>) : <ThemedText type="small">No staff features are currently enabled for this account.</ThemedText>}<Pressable onPress={() => void logout()} style={styles.secondary}><ThemedText>Sign out</ThemedText></Pressable></View></>}<ThemedText type="small">{message}</ThemedText></ScrollView></SafeAreaView></ThemedView>;
}

const styles = StyleSheet.create({ screen: { flex: 1 }, safe: { flex: 1 }, content: { padding: 24, gap: 20 }, header: { gap: 8, paddingTop: 32 }, card: { backgroundColor: '#DFF3E7', borderRadius: 24, padding: 22, gap: 12 }, input: { backgroundColor: '#fff', borderColor: '#94A3B8', borderWidth: 1, borderRadius: 12, padding: 14, color: '#0F172A' }, button: { backgroundColor: '#166534', borderRadius: 12, padding: 14, alignItems: 'center' }, buttonText: { color: '#fff' }, secondary: { borderWidth: 1, borderColor: '#64748B', borderRadius: 12, padding: 12, alignItems: 'center' }, choice: { borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 14, padding: 14, gap: 3 }, selected: { borderColor: '#166534', backgroundColor: '#fff' }, tile: { borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 18, padding: 18, gap: 4 } });
