export type SuiteGroup = "Manage" | "Academics" | "People" | "Finance" | "Operations" | "Engagement" | "Platform";
export type SuiteNavigationItem = { label: string; shortLabel: string; group: SuiteGroup; href?: string; portalHref?: string };
export const suiteGroups: SuiteGroup[] = ["Manage", "Academics", "People", "Finance", "Operations", "Engagement", "Platform"];
export const suiteNavigation: SuiteNavigationItem[] = [
  { label: "School administration", shortLabel: "School", group: "Manage", href: "/portal/school", portalHref: "/portal/school" },
  { label: "Admissions & enrolment", shortLabel: "Admissions", group: "Manage", href: "/portal/admissions", portalHref: "/portal/admissions" },
  { label: "Student information (SIS)", shortLabel: "Students", group: "People", href: "/portal/students", portalHref: "/portal/students" },
  { label: "Parents & guardians", shortLabel: "Guardians", group: "People", href: "/portal/guardians", portalHref: "/portal/guardians" },
  { label: "Academic structure", shortLabel: "Academics", group: "Academics", href: "/portal/academics", portalHref: "/portal/academics" },
  { label: "Timetable & scheduling", shortLabel: "Timetable", group: "Academics" },
  { label: "Student attendance", shortLabel: "Attendance", group: "Academics" },
  { label: "Teaching & curriculum", shortLabel: "Teaching", group: "Academics", href: "/portal/teaching", portalHref: "/portal/teaching" },
  { label: "Assignments & homework", shortLabel: "Assignments", group: "Academics" },
  { label: "Learning management (LMS)", shortLabel: "LMS", group: "Academics" },
  { label: "Assessment & gradebook", shortLabel: "Gradebook", group: "Academics" },
  { label: "Computer-based testing", shortLabel: "CBT", group: "Academics" },
  { label: "Report cards & certificates", shortLabel: "Report cards", group: "Academics" },
  { label: "Fees & billing", shortLabel: "Fees", group: "Finance", href: "/portal/commercial", portalHref: "/portal/commercial" },
  { label: "Online payments", shortLabel: "Payments", group: "Finance" },
  { label: "Accounting & finance", shortLabel: "Accounting", group: "Finance", href: "/portal/commercial", portalHref: "/portal/commercial" },
  { label: "HR & staff management", shortLabel: "Staff", group: "People", href: "/portal/staff", portalHref: "/portal/staff" },
  { label: "Staff attendance & leave", shortLabel: "Staff leave", group: "People", href: "/portal/staff-self-service", portalHref: "/portal/staff-self-service" },
  { label: "Payroll", shortLabel: "Payroll", group: "Finance" },
  { label: "Communication hub", shortLabel: "Communication", group: "Engagement" },
  { label: "School chat & collaboration", shortLabel: "School chat", group: "Engagement" },
  { label: "Behaviour & student welfare", shortLabel: "Student welfare", group: "People" },
  { label: "Health & medical records", shortLabel: "Health", group: "People" },
  { label: "Library management", shortLabel: "Library", group: "Operations" },
  { label: "Inventory & assets", shortLabel: "Inventory", group: "Operations" },
  { label: "Procurement & vendors", shortLabel: "Procurement", group: "Operations" },
  { label: "Transportation", shortLabel: "Transport", group: "Operations" },
  { label: "Hostel & boarding", shortLabel: "Hostel", group: "Operations" },
  { label: "Canteen & meals", shortLabel: "Canteen", group: "Operations" },
  { label: "School store", shortLabel: "School store", group: "Operations" },
  { label: "Facilities & maintenance", shortLabel: "Facilities", group: "Operations" },
  { label: "Visitor, gate & security", shortLabel: "Security", group: "Operations" },
  { label: "Events & school calendar", shortLabel: "Events", group: "Engagement" },
  { label: "Clubs, houses & sports", shortLabel: "Activities", group: "Engagement" },
  { label: "Student leave & movement", shortLabel: "Student leave", group: "People" },
  { label: "Document management", shortLabel: "Documents", group: "Operations" },
  { label: "Workflow & approvals", shortLabel: "Approvals", group: "Operations" },
  { label: "School website & CMS", shortLabel: "Website", group: "Engagement" },
  { label: "Surveys & feedback", shortLabel: "Surveys", group: "Engagement" },
  { label: "Helpdesk & complaints", shortLabel: "Helpdesk", group: "Engagement" },
  { label: "Alumni management", shortLabel: "Alumni", group: "People" },
  { label: "Analytics & reporting", shortLabel: "Analytics", group: "Manage" },
  { label: "AI & automation", shortLabel: "Giddy AI", group: "Platform" },
  { label: "Portals & mobile experience", shortLabel: "Apps", group: "Platform" },
  { label: "Integrations & API", shortLabel: "Integrations", group: "Platform" },
  { label: "Security & compliance", shortLabel: "Security", group: "Platform", href: "/portal/operations", portalHref: "/portal/operations" },
  { label: "Subscription & plan", shortLabel: "Subscription", group: "Platform", href: "/portal/subscription", portalHref: "/portal/subscription" },
];
