import { LegalPage, type LegalSection } from "@/components/legal-page";

const sections: LegalSection[] = [
  { title: "Using GiddyEdu", paragraphs: ["These terms govern access to GiddyEdu by subscribing schools and authorised users. A school’s order, subscription or service agreement may contain additional commercial terms and will control where it expressly differs from these terms."] },
  { title: "Accounts and access", paragraphs: ["Users must provide accurate information, protect their credentials and promptly report suspected unauthorised access. Schools control their memberships, roles and permissions. Accounts may not be shared or used outside the authority granted by the school."] },
  { title: "Acceptable use", paragraphs: ["GiddyEdu must not be used to break the law, harm others, interfere with the service, bypass security controls, access another tenant, distribute malicious material or process information without appropriate authority."] },
  { title: "School information", paragraphs: ["Schools retain their rights in information submitted to the service and grant GiddyEdu the limited authority needed to host, process, secure, back up and transmit that information to provide the platform.", "Schools are responsible for the accuracy, legality and authorised use of the information they and their users provide."] },
  { title: "Subscriptions and payment", paragraphs: ["Access to paid capabilities depends on the selected plan, enabled features, usage limits and payment status. Pricing, billing periods, renewal, taxes, suspension and cancellation arrangements are defined by the applicable order or subscription terms."] },
  { title: "Service operation", paragraphs: ["GiddyEdu may maintain, improve or update the platform and may temporarily restrict access where reasonably necessary for security, maintenance, legal compliance or protection of the service. Reasonable efforts will be made to minimise disruption."] },
  { title: "Intellectual property", paragraphs: ["GiddyEdu and its licensors retain rights in the platform, software, designs, documentation and branding. These terms grant only a limited, non-exclusive right to use the service during an authorised subscription."] },
  { title: "Suspension and termination", paragraphs: ["Access may be suspended or terminated for non-payment, material breach, security risk, unlawful activity or as otherwise permitted by the applicable agreement. Following termination, data handling and export are governed by the subscription agreement and retention arrangements."] },
  { title: "Responsibility and changes", paragraphs: ["Service warranties, liability limits, support commitments and dispute arrangements are set out in the applicable service agreement to the extent permitted by law.", "These terms may be updated when the service or legal requirements change. Material changes will be communicated through an appropriate service channel."] },
];

export default function TermsPage() { return <LegalPage title="Terms & Conditions" introduction="These terms describe the rules and responsibilities that apply when a school or authorised user accesses GiddyEdu." sections={sections} />; }
