import { ResourcePage } from "@/components/resource-page";
import { AdmissionFormSettings } from "@/components/admission-form-settings";

export default function AdmissionsPage() {
  return <><AdmissionFormSettings /><ResourcePage title="Admissions" description="Screen applicants, manage decisions, and convert accepted applications into canonical student records." endpoint="admissions/applicants?page=1&pageSize=50" emptyMessage="No applications have been submitted." fields={[{key:"applicationNumber",label:"Application"},{key:"firstName",label:"First name"},{key:"lastName",label:"Last name"},{key:"status",label:"Status"}]} create={{ endpoint:"admissions/applicants", title:"Add applicant", fields:[{name:"applicationNumber",label:"Application number"},{name:"firstName",label:"First name"},{name:"lastName",label:"Last name"},{name:"dateOfBirth",label:"Date of birth",type:"date"},{name:"email",label:"Email",type:"email",required:false},{name:"phone",label:"Phone",required:false},{name:"previousSchool",label:"Previous school",required:false},{name:"source",label:"Admission source",required:false}] }} actions={[
    { endpoint:"admissions/applicants/{id}/status", method:"PUT", title:"Change status", fields:[{name:"status",label:"New status",type:"select",numeric:true,options:[{value:"2",label:"Under review"},{value:"3",label:"Waitlisted"},{value:"7",label:"Withdrawn"}]}] },
    { endpoint:"admissions/applicants/{id}/review", method:"PUT", title:"Record screening", fields:[{name:"score",label:"Score (0–100)",type:"number",numeric:true},{name:"screeningNotes",label:"Screening notes",required:false}] },
    { endpoint:"admissions/applicants/{id}/interviews", title:"Schedule interview", fields:[{name:"scheduledAtUtc",label:"Interview date and time"},{name:"location",label:"Location",required:false}] },
    { endpoint:"admissions/applicants/{id}/communications", title:"Send email", fields:[{name:"type",label:"Message type",type:"select",numeric:true,options:[{value:"0",label:"General"},{value:"1",label:"Interview"},{value:"2",label:"Offer"},{value:"3",label:"Decision"}]},{name:"subject",label:"Subject"},{name:"message",label:"Message"}] },
    { endpoint:"admissions/applicants/{id}/offer", title:"Issue admission offer", fields:[{name:"validForDays",label:"Valid for days (1–90)",type:"number",numeric:true}] },
    { endpoint:"admissions/applicants/{id}/reject", title:"Reject application" },
    { endpoint:"documents/Applicant/{id}/uploads", title:"Upload document", documentUpload:true, fields:[{name:"category",label:"Category",type:"select",options:[{value:"admission",label:"Admission"},{value:"identity",label:"Identity"},{value:"medical",label:"Medical"},{value:"photo",label:"Photograph"},{value:"other",label:"Other"}]},{name:"file",label:"PDF, JPEG, or PNG (maximum 10 MB)",type:"file"}] },
    { endpoint:"admissions/applicants/{id}/convert", title:"Enrol accepted applicant", fields:[{name:"admissionNumber",label:"Admission number"},{name:"academicYearId",label:"Academic year",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"academicYears"},{name:"classSectionId",label:"Class section",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"classSections"},{name:"enrolledOn",label:"Enrolment date",type:"date"}] }
  ]} /></>;
}
