import { ResourcePage } from "@/components/resource-page";

export default function AcademicsPage() {
  return <ResourcePage title="Academic structure" description="Configure the school calendar, Nigerian education stages, classes, departments, and subjects." endpoint="academics/structure" collectionKey="academicYears" emptyMessage="No academic year has been configured." fields={[{key:"name",label:"Academic year"},{key:"startsOn",label:"Starts"},{key:"endsOn",label:"Ends"},{key:"status",label:"Status"}]} create={{ endpoint:"academics/years", title:"Add academic year", fields:[{name:"name",label:"Name"},{name:"startsOn",label:"Start date",type:"date"},{name:"endsOn",label:"End date",type:"date"}] }} creates={[
    { endpoint:"academics/terms", title:"Add term", fields:[{name:"academicYearId",label:"Academic year",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"academicYears"},{name:"name",label:"Name"},{name:"code",label:"Code"},{name:"sequence",label:"Sequence",type:"number",numeric:true},{name:"startsOn",label:"Start date",type:"date"},{name:"endsOn",label:"End date",type:"date"}] },
    { endpoint:"academics/education-stages", title:"Add education stage", fields:[{name:"name",label:"Name"},{name:"code",label:"Code"},{name:"displayOrder",label:"Display order",type:"number",numeric:true}] },
    { endpoint:"academics/class-levels", title:"Add class level", fields:[{name:"educationStageId",label:"Education stage",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"educationStages"},{name:"name",label:"Name"},{name:"code",label:"Code"},{name:"displayOrder",label:"Display order",type:"number",numeric:true}] },
    { endpoint:"academics/departments", title:"Add department", fields:[{name:"name",label:"Name"},{name:"code",label:"Code"}] },
    { endpoint:"academics/subjects", title:"Add subject", fields:[{name:"departmentId",label:"Department",type:"select",required:false,optionsEndpoint:"academics/structure",optionsCollectionKey:"departments"},{name:"name",label:"Name"},{name:"code",label:"Code"},{name:"isCore",label:"Subject type",type:"select",options:[{value:"true",label:"Core"},{value:"false",label:"Elective"}]}] },
    { endpoint:"academics/class-sections", title:"Add class section", fields:[{name:"campusId",label:"Campus",type:"select",optionsEndpoint:"schools/campuses"},{name:"academicYearId",label:"Academic year",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"academicYears"},{name:"classLevelId",label:"Class level",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"classLevels"},{name:"name",label:"Name"},{name:"code",label:"Code"},{name:"capacity",label:"Capacity",type:"number",numeric:true,required:false}] },
    { endpoint:"academics/class-subjects", method:"PUT", title:"Assign subject to class", fields:[{name:"classSectionId",label:"Class section",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"classSections"},{name:"subjectId",label:"Subject",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"subjects"},{name:"isCompulsory",label:"Requirement",type:"select",options:[{value:"true",label:"Compulsory"},{value:"false",label:"Elective"}]}] }
  ]} />;
}
