"use client";

import { useState } from "react";
import { ResourcePage, type CreateConfig, type RecordActionConfig } from "@/components/resource-page";

const resources: { key: string; title: string; description: string; collection: string; fields: { key: string; label: string }[]; create: CreateConfig; actions: RecordActionConfig[] }[] = [
  entry("years", "Academic years", "Create and maintain the school calendar.", "academicYears", [{key:"name",label:"Name"},{key:"startsOn",label:"Starts"},{key:"endsOn",label:"Ends"},{key:"status",label:"Status"}], [{name:"name",label:"Name"},{name:"startsOn",label:"Start date",type:"date"},{name:"endsOn",label:"End date",type:"date"}]),
  entry("terms", "Terms", "Manage terms within each academic year.", "terms", [{key:"name",label:"Name"},{key:"code",label:"Code"},{key:"sequence",label:"Sequence"},{key:"startsOn",label:"Starts"},{key:"endsOn",label:"Ends"}], [{name:"academicYearId",label:"Academic year",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"academicYears"},{name:"name",label:"Name"},{name:"code",label:"Code"},{name:"sequence",label:"Sequence",type:"number",numeric:true},{name:"startsOn",label:"Start date",type:"date"},{name:"endsOn",label:"End date",type:"date"}]),
  entry("education-stages", "Education stages", "Organise nursery, primary and secondary stages.", "educationStages", [{key:"name",label:"Name"},{key:"code",label:"Code"},{key:"displayOrder",label:"Order"}], [{name:"name",label:"Name"},{name:"code",label:"Code"},{name:"displayOrder",label:"Display order",type:"number",numeric:true}]),
  entry("class-levels", "Class levels", "Maintain levels within each education stage.", "classLevels", [{key:"name",label:"Name"},{key:"code",label:"Code"},{key:"displayOrder",label:"Order"}], [{name:"educationStageId",label:"Education stage",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"educationStages"},{name:"name",label:"Name"},{name:"code",label:"Code"},{name:"displayOrder",label:"Display order",type:"number",numeric:true}]),
  entry("class-sections", "Class sections", "Configure campus classes for an academic year.", "classSections", [{key:"name",label:"Name"},{key:"code",label:"Code"},{key:"capacity",label:"Capacity"}], [{name:"campusId",label:"Campus",type:"select",optionsEndpoint:"schools/campuses"},{name:"academicYearId",label:"Academic year",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"academicYears"},{name:"classLevelId",label:"Class level",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"classLevels"},{name:"name",label:"Name"},{name:"code",label:"Code"},{name:"capacity",label:"Capacity",type:"number",numeric:true,required:false}]),
  entry("departments", "Departments", "Maintain academic and staff departments.", "departments", [{key:"name",label:"Name"},{key:"code",label:"Code"}], [{name:"name",label:"Name"},{name:"code",label:"Code"}]),
  entry("subjects", "Subjects", "Maintain core and elective subjects.", "subjects", [{key:"name",label:"Name"},{key:"code",label:"Code"},{key:"isCore",label:"Core"}], [{name:"departmentId",label:"Department",type:"select",required:false,optionsEndpoint:"academics/structure",optionsCollectionKey:"departments"},{name:"name",label:"Name"},{name:"code",label:"Code"},{name:"isCore",label:"Subject type",type:"select",options:[{value:"true",label:"Core"},{value:"false",label:"Elective"}]}]),
  { key:"class-subjects", title:"Class subjects", description:"Assign subjects to class sections.", collection:"classSubjects", fields:[{key:"classSectionId",label:"Class section"},{key:"subjectId",label:"Subject"},{key:"isCompulsory",label:"Compulsory"}], create:{endpoint:"academics/class-subjects",title:"Assign subject",method:"PUT",fields:[{name:"classSectionId",label:"Class section",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"classSections"},{name:"subjectId",label:"Subject",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"subjects"},{name:"isCompulsory",label:"Requirement",type:"select",options:[{value:"true",label:"Compulsory"},{value:"false",label:"Elective"}]}]}, actions:[{endpoint:"academics/class-subjects",title:"Update",method:"PUT",fields:[{name:"classSectionId",label:"Class section",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"classSections"},{name:"subjectId",label:"Subject",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"subjects"},{name:"isCompulsory",label:"Requirement",type:"select",options:[{value:"true",label:"Compulsory"},{value:"false",label:"Elective"}]}]},{endpoint:"academics/class-subjects/{classSectionId}/{subjectId}",title:"Delete",method:"DELETE",dangerous:true}] },
];

function entry(key: string, title: string, description: string, collection: string, fields: { key: string; label: string }[], formFields: CreateConfig["fields"]) {
  return { key, title, description, collection, fields, create: { endpoint: `academics/${key}`, title: `Add ${title.toLowerCase().replace(/s$/, "")}`, fields: formFields }, actions: [
    { endpoint: `academics/${key}/{id}`, title: "Edit", method: "PUT" as const, fields: formFields },
    { endpoint: `academics/${key}/{id}`, title: "Delete", method: "DELETE" as const, dangerous: true },
  ] };
}

export function AcademicStructureWorkspace() {
  const [selected, setSelected] = useState(resources[0].key); const resource = resources.find(value => value.key === selected) ?? resources[0];
  return <section><nav className="flex flex-wrap gap-2 bg-[#f6f4ee] px-6 pt-6" aria-label="Academic structure categories">{resources.map(value => <button key={value.key} type="button" onClick={() => setSelected(value.key)} className={`rounded-full px-4 py-2 text-sm font-bold ${selected === value.key ? "bg-[#12372a] text-white" : "border border-slate-300 bg-white text-slate-700 hover:border-emerald-600"}`}>{value.title}</button>)}</nav><ResourcePage title={resource.title} description={resource.description} endpoint="academics/structure" collectionKey={resource.collection} emptyMessage={`No ${resource.title.toLowerCase()} have been configured.`} fields={resource.fields} create={resource.create} actions={resource.actions} /></section>;
}
