"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ResourcePage, type CreateConfig, type RecordActionConfig } from "@/components/resource-page";

const resources: { key: string; title: string; description: string; collection: string; fields: { key: string; label: string }[]; create: CreateConfig; actions: RecordActionConfig[] }[] = [
  entry("years", "Academic years", "Create and maintain the school calendar using a recognised academic session.", "academicYears", [{key:"name",label:"Academic session"},{key:"startsOn",label:"Starts"},{key:"endsOn",label:"Ends"},{key:"statusLabel",label:"Status"}], [{name:"name",label:"Academic session",type:"academicYear",helper:"Choose a session from the current range. Use the arrows to browse earlier or later years without any fixed end date."},{name:"startsOn",label:"Session start date",type:"date",helper:"The first official day of this academic session."},{name:"endsOn",label:"Session end date",type:"date",helper:"The final official day of this academic session."}]),
  entry("terms", "Terms", "Manage terms within each academic year.", "terms", [{key:"name",label:"Term name"},{key:"code",label:"Term code"},{key:"sequence",label:"Order"},{key:"startsOn",label:"Starts"},{key:"endsOn",label:"Ends"},{key:"statusLabel",label:"Status"}], [{name:"academicYearId",label:"Academic year",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"academicYears"},{name:"name",label:"Term name",helper:"Use the name your school community recognises, for example First Term."},{name:"code",label:"Term code",helper:"A short identifier used in reports, for example T1 or TERM-1."},{name:"sequence",label:"Order in academic year",type:"number",numeric:true,helper:"Enter 1 for the first term, 2 for the second and 3 for the third."},{name:"startsOn",label:"Start date",type:"date"},{name:"endsOn",label:"End date",type:"date"}]),
  entry("education-stages", "Education stages", "Select the standard education stages operated by this school. GiddyEdu manages their technical codes and ordering automatically.", "educationStages", [{key:"name",label:"Education stage"}], [{name:"name",label:"Education stage",type:"select",helper:"Choose a stage. Its internal code and position are protected and managed automatically.",options:[{value:"Creche / Early Years",label:"Creche / Early Years"},{value:"Nursery",label:"Nursery"},{value:"Primary",label:"Primary"},{value:"Junior Secondary",label:"Junior Secondary (JSS)"},{value:"Senior Secondary",label:"Senior Secondary (SSS)"},{value:"Sixth Form",label:"Sixth Form"}]}]),
  entry("class-levels", "Class levels", "Choose the year groups taught within each education stage. GiddyEdu protects their internal codes and ordering automatically.", "classLevels", [{key:"educationStageName",label:"Education stage"},{key:"name",label:"Class level"}], [{name:"educationStageId",label:"Education stage",type:"select",helper:"First choose the stage this level belongs to.",optionsEndpoint:"academics/structure",optionsCollectionKey:"educationStages"},{name:"name",label:"Class level",type:"select",dependsOn:"educationStageId",helper:"Only levels belonging to the selected education stage are shown.",options:[{value:"Creche",label:"Creche",context:"Creche / Early Years"},{value:"Playgroup",label:"Playgroup",context:"Creche / Early Years"},{value:"Reception",label:"Reception",context:"Creche / Early Years"},{value:"Nursery 1",label:"Nursery 1",context:"Nursery"},{value:"Nursery 2",label:"Nursery 2",context:"Nursery"},{value:"Primary 1",label:"Primary 1",context:"Primary"},{value:"Primary 2",label:"Primary 2",context:"Primary"},{value:"Primary 3",label:"Primary 3",context:"Primary"},{value:"Primary 4",label:"Primary 4",context:"Primary"},{value:"Primary 5",label:"Primary 5",context:"Primary"},{value:"Primary 6",label:"Primary 6",context:"Primary"},{value:"JSS 1",label:"JSS 1",context:"Junior Secondary"},{value:"JSS 2",label:"JSS 2",context:"Junior Secondary"},{value:"JSS 3",label:"JSS 3",context:"Junior Secondary"},{value:"SS 1",label:"SS 1",context:"Senior Secondary"},{value:"SS 2",label:"SS 2",context:"Senior Secondary"},{value:"SS 3",label:"SS 3",context:"Senior Secondary"},{value:"Lower Sixth",label:"Lower Sixth",context:"Sixth Form"},{value:"Upper Sixth",label:"Upper Sixth",context:"Sixth Form"}]}]),
  entry("class-sections", "Class sections", "Create arms and streams inside the current campus and active academic year. GiddyEdu generates the complete class name and code.", "classSections", [{key:"classLevelName",label:"Class level"},{key:"name",label:"Section"},{key:"capacity",label:"Capacity"}], [{name:"classLevelId",label:"Class level",type:"select",helper:"Choose the parent level, such as JSS 2 or SS 2.",optionsEndpoint:"academics/structure",optionsCollectionKey:"classLevels"},{name:"name",label:"Name / arm / stream",placeholder:"Example: A, Gold, Science or Arts",helper:"Enter only the arm or stream. GiddyEdu will create names such as JSS 2A or SS 2 Science."},{name:"capacity",label:"Maximum capacity",type:"number",numeric:true,required:false,placeholder:"Example: 35"}]),
  entry("departments", "Departments", "Create the teams that organise subjects and staff. GiddyEdu generates and protects the technical code.", "departments", [{key:"name",label:"Department name"}], [{name:"name",label:"Department name",placeholder:"Example: Sciences, Languages or Humanities",helper:"Use a clear name recognised by staff. The internal code is created automatically and remains stable."}]),
  entry("subjects", "Subjects", "Create the subjects taught by the school. GiddyEdu generates and protects the technical code.", "subjects", [{key:"name",label:"Subject name"},{key:"isCore",label:"Subject type"}], [{name:"departmentId",label:"Department",type:"select",required:false,helper:"Optionally group this subject under a department.",optionsEndpoint:"academics/structure",optionsCollectionKey:"departments"},{name:"name",label:"Subject name",placeholder:"Example: Mathematics, English Language or Basic Science",helper:"Enter the official subject name used on timetables and reports."},{name:"isCore",label:"Subject type",type:"select",options:[{value:"true",label:"Core"},{value:"false",label:"Elective"}]}]),
  { key:"class-subjects", title:"Class subjects", description:"Assign subjects to class sections.", collection:"classSubjects", fields:[{key:"classSectionName",label:"Class section"},{key:"subjectName",label:"Subject"},{key:"requirement",label:"Requirement"}], create:{endpoint:"academics/class-subjects",title:"Assign subject",method:"PUT",fields:[{name:"classSectionId",label:"Class section",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"classSections"},{name:"subjectId",label:"Subject",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"subjects"},{name:"isCompulsory",label:"Requirement",type:"select",options:[{value:"true",label:"Compulsory"},{value:"false",label:"Elective"}]}]}, actions:[{endpoint:"academics/class-subjects",title:"Update",method:"PUT",fields:[{name:"classSectionId",label:"Class section",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"classSections"},{name:"subjectId",label:"Subject",type:"select",optionsEndpoint:"academics/structure",optionsCollectionKey:"subjects"},{name:"isCompulsory",label:"Requirement",type:"select",options:[{value:"true",label:"Compulsory"},{value:"false",label:"Elective"}]}]},{endpoint:"academics/class-subjects/{classSectionId}/{subjectId}",title:"Delete",method:"DELETE",dangerous:true}] },
];

function entry(key: string, title: string, description: string, collection: string, fields: { key: string; label: string }[], formFields: CreateConfig["fields"]) {
  return { key, title, description, collection, fields, create: { endpoint: `academics/${key}`, title: `Add ${title.toLowerCase().replace(/s$/, "")}`, fields: formFields }, actions: [
    ...(["years", "terms"].includes(key) ? [{ endpoint: `academics/${key}/{id}/activate`, title: "Set active", method: "POST" as const }] : []),
    { endpoint: `academics/${key}/{id}`, title: "Edit", method: "PUT" as const, fields: formFields },
    { endpoint: `academics/${key}/{id}`, title: "Delete", method: "DELETE" as const, dangerous: true },
  ] };
}

export function AcademicStructureWorkspace() {
  const router = useRouter(); const searchParams = useSearchParams();
  const selected = searchParams.get("section") ?? resources[0].key;
  const [structure, setStructure] = useState<Record<string, unknown[]>>({}); const resource = resources.find(value => value.key === selected) ?? resources[0];
  useEffect(() => { const load = () => fetch("/api/backend/academics/structure", { cache:"no-store" }).then(async response => { if (response.ok) setStructure(await response.json() as Record<string, unknown[]>); }); void load(); window.addEventListener("giddyedu:academic-context-changed", load); return () => window.removeEventListener("giddyedu:academic-context-changed", load); }, []);
  const configured = useMemo(() => resources.slice(0, 7).reduce((total, item) => total + (structure[item.collection]?.length ?? 0), 0), [structure]);
  const activeYear = (structure.academicYears as { name:string; status:number|string }[] | undefined)?.find(item => item.status === 1 || item.status === "Active");
  const activeTerm = (structure.terms as { name:string; status:number|string }[] | undefined)?.find(item => item.status === 1 || item.status === "Active");
  return <section className="space-y-6"><header className="relative overflow-hidden rounded-[1.75rem] bg-[#12372a] px-6 py-7 text-white shadow-[0_24px_60px_rgba(18,55,42,.16)] sm:px-8 sm:py-9"><div className="absolute -right-16 -top-24 size-72 rounded-full border-[48px] border-white/[.04]" /><div className="relative flex flex-col gap-7 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-200">Academic configuration</p><h1 className="mt-3 text-3xl font-black tracking-[-.04em] sm:text-4xl">Build your school structure</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/70 sm:text-base">Manage the calendar, education stages, classes and subjects that power enrolment, teaching and reporting.</p></div><dl className="grid grid-cols-3 gap-2 sm:gap-3"><Summary label="Active session" value={activeYear?.name ?? "Not set"} /><Summary label="Active term" value={activeTerm?.name ?? "Not set"} /><Summary label="Configured" value={String(configured)} /></dl></div></header><div className="grid gap-5 xl:grid-cols-[16rem_minmax(0,1fr)]"><aside className="h-fit rounded-2xl border border-[#dfe6e1] bg-white p-3 shadow-[0_10px_30px_rgba(28,53,42,.05)]"><p className="px-3 pb-2 pt-2 text-[11px] font-black uppercase tracking-[.16em] text-[#718078]">Structure</p><nav className="space-y-1" aria-label="Academic structure categories">{resources.map(value => { const active = resource.key === value.key; return <button key={value.key} type="button" onClick={() => router.replace(`/portal/academics?section=${value.key}`, { scroll: false })} className={`flex w-full items-center justify-between rounded-xl px-3 py-3 text-left text-sm font-bold transition ${active ? "bg-[#12372a] text-white shadow-sm" : "text-[#4d5d54] hover:bg-[#f0f5f1] hover:text-[#173d2f]"}`}><span>{value.title}</span><span className={`rounded-full px-2 py-0.5 text-[10px] ${active ? "bg-white/15" : "bg-[#edf2ee] text-[#66766d]"}`}>{structure[value.collection]?.length ?? 0}</span></button>})}</nav></aside><div className="min-w-0 rounded-2xl border border-[#dfe6e1] bg-white p-5 shadow-[0_10px_30px_rgba(28,53,42,.05)] sm:p-7"><div className="[&>main]:min-h-0 [&>main]:bg-transparent [&>main>header]:hidden [&>main>div]:mx-0 [&>main>div]:max-w-none [&>main>div]:px-0 [&>main>div]:py-0"><ResourcePage title={resource.title} description={resource.description} endpoint="academics/structure" collectionKey={resource.collection} emptyMessage={`No ${resource.title.toLowerCase()} have been configured.`} fields={resource.fields} create={resource.create} actions={resource.actions} /></div></div></div></section>;
}

function Summary({ label, value }: { label:string; value:string }) { return <div className="min-w-0 rounded-xl border border-white/12 bg-white/[.08] px-3 py-3 backdrop-blur-sm sm:min-w-28 sm:px-4"><dt className="text-[9px] font-black uppercase tracking-[.13em] text-white/55">{label}</dt><dd className="mt-1 truncate text-xs font-black sm:text-sm">{value}</dd></div>; }
