"use client";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";

type Offer = { schoolName: string; applicantName: string; applicationNumber: string; expiresAtUtc: string; response: number; primaryColor?: string; secondaryColor?: string };
export function AdmissionOfferResponse() {
  const token = useSearchParams().get("token") ?? ""; const [offer, setOffer] = useState<Offer | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!token) return; void fetch(`/api/public/admission-offer?token=${encodeURIComponent(token)}`, { cache: "no-store" }).then(async response => { if (!response.ok) throw new Error("This offer link is invalid or unavailable."); setOffer(await response.json() as Offer); }).catch(error => setMessage(error instanceof Error ? error.message : "Offer unavailable.")); }, [token]);
  async function respond(accepted: boolean) { setBusy(true); const response = await fetch(`/api/public/admission-offer?token=${encodeURIComponent(token)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ accepted }) }); setBusy(false); if (!response.ok) { setMessage("This offer has expired or already received a response."); return; } setOffer(current => current ? { ...current, response: accepted ? 1 : 2 } : current); setMessage(accepted ? "Offer accepted. The school will contact you with enrolment steps." : "Offer declined. The school has been notified."); }
  if (!offer) return <main className="min-h-screen bg-[#f6f4ee] p-8"><div className="mx-auto max-w-2xl rounded-3xl bg-white p-8">{!token ? "This offer link is invalid." : message || "Loading admission letter…"}</div></main>;
  const primary = offer.primaryColor ?? "#12372A"; return <main className="min-h-screen bg-[#f6f4ee] px-6 py-12"><article className="mx-auto max-w-3xl overflow-hidden rounded-3xl bg-white shadow-xl"><header className="p-8 text-white" style={{ background: `linear-gradient(135deg, ${primary}, ${offer.secondaryColor ?? "#10B981"})` }}><p className="text-sm uppercase tracking-widest">Admission offer</p><h1 className="mt-2 text-3xl font-black">{offer.schoolName}</h1></header><div className="space-y-5 p-8"><p>Dear <strong>{offer.applicantName}</strong>,</p><p>We are pleased to offer you admission. Your application reference is <strong>{offer.applicationNumber}</strong>.</p><p>This offer must be accepted by <strong>{new Date(offer.expiresAtUtc).toLocaleDateString()}</strong>.</p>{offer.response === 0 ? <div className="flex flex-wrap gap-3 border-t pt-6"><button disabled={busy} onClick={() => void respond(true)} className="rounded-xl px-5 py-3 font-bold text-white disabled:opacity-50" style={{ backgroundColor: primary }}>Accept offer</button><button disabled={busy} onClick={() => void respond(false)} className="rounded-xl border border-slate-300 px-5 py-3 font-bold disabled:opacity-50">Decline offer</button></div> : <p className="rounded-xl bg-emerald-50 p-4 font-bold">Response recorded: {offer.response === 1 ? "Accepted" : "Declined"}</p>}{message && <p role="status" className="rounded-xl bg-slate-50 p-4">{message}</p>}</div></article></main>;
}
