"use client";
import { FormEvent, useEffect, useState } from "react";

type Definition = { id: string; fieldKey: string; label: string; dataType: number; isRequired: boolean; isActive: boolean };
const types = [{ value: 0, label: "Short text" }, { value: 1, label: "Long text" }, { value: 2, label: "Whole number" }, { value: 3, label: "Decimal" }, { value: 4, label: "Date" }, { value: 6, label: "Yes / No" }, { value: 7, label: "Email" }, { value: 8, label: "Phone" }, { value: 9, label: "Website" }, { value: 10, label: "Single choice" }, { value: 11, label: "Multiple choice" }];

export function AdmissionFormSettings() {
  const [definitions, setDefinitions] = useState<Definition[]>([]); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/backend/foundation/custom-fields?entityType=Applicant", { cache: "no-store" }); if (response.ok) setDefinitions(await response.json() as Definition[]); }
  useEffect(() => { void fetch("/api/backend/foundation/custom-fields?entityType=Applicant", { cache: "no-store" }).then(async response => { if (response.ok) setDefinitions(await response.json() as Definition[]); }); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = event.currentTarget; const data = new FormData(form); const dataType = Number(data.get("dataType")); const optionLabels = String(data.get("options") ?? "").split(",").map(value => value.trim()).filter(Boolean); const payload = { targetModule: "Admissions", targetEntityType: "Applicant", fieldKey: data.get("fieldKey"), label: data.get("label"), helpText: data.get("helpText") || null, dataType, isRequired: data.get("isRequired") === "on", isActive: true, displayOrder: definitions.length, defaultValue: null, validation: null, options: dataType === 10 || dataType === 11 ? optionLabels.map((label, index) => ({ value: label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""), label, displayOrder: index })) : [] }; const response = await fetch("/api/backend/foundation/custom-fields", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); setBusy(false); if (!response.ok) { setMessage(response.status === 403 ? "CustomFields.Manage permission is required." : "The field could not be created. Check its key and options."); return; } form.reset(); setOpen(false); setMessage("Application field created."); await load(); }
  return <section className="bg-[#edf5ef] px-6 py-6"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-800">Public application form</p><p className="mt-1 text-sm text-slate-600">{definitions.length} configured field(s) are shown securely on the school&apos;s public form.</p></div><button type="button" onClick={() => setOpen(value => !value)} className={`rounded-xl px-4 py-2 font-bold text-white ${open ? "bg-red-700 hover:bg-red-800" : "bg-emerald-800"}` }>{open ? "Cancel" : "Configure field"}</button></div>{definitions.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{definitions.map(field => <span key={field.id} className="rounded-full bg-white px-3 py-2 text-xs font-semibold">{field.label}{field.isRequired ? " · Required" : ""}{!field.isActive ? " · Inactive" : ""}</span>)}</div>}{open && <form onSubmit={submit} className="mt-5 grid gap-4 rounded-2xl bg-white p-5 sm:grid-cols-2"><label className="text-sm font-semibold">Field key<input name="fieldKey" required pattern="[a-z][a-z0-9_]{0,63}" placeholder="preferred_language" className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-sm font-semibold">Label<input name="label" required placeholder="Preferred language" className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-sm font-semibold">Field type<select name="dataType" className="mt-1 w-full rounded-xl border bg-white px-3 py-2">{types.map(type => <option key={type.value} value={type.value}>{type.label}</option>)}</select></label><label className="text-sm font-semibold">Help text<input name="helpText" className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="sm:col-span-2 text-sm font-semibold">Choice options, comma separated<input name="options" placeholder="English, Hausa, Igbo, Yoruba" className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-sm font-semibold"><input name="isRequired" type="checkbox" className="mr-2" />Required on public form</label><button disabled={busy} className="rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white disabled:opacity-50">{busy ? "Saving…" : "Add field"}</button></form>}{message && <p role="status" className="mt-3 text-sm">{message}</p>}</div></section>;
}
