"use client";
import { FormEvent, useEffect, useState } from "react";

type FormField = { fieldKey: string; label: string; helpText?: string; dataType: number; isRequired: boolean; defaultValue?: string; options: { value: string; label: string }[] };

export function ApplicationForm({ tenantSlug }: { tenantSlug: string }) {
  const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [reference, setReference] = useState(""); const [fields, setFields] = useState<FormField[]>([]);
  useEffect(() => { fetch(`/api/public/admissions/${tenantSlug}`, { cache: "no-store" }).then(async response => { if (!response.ok) throw new Error("This school is not accepting online applications."); setFields(await response.json() as FormField[]); }).catch(value => setError(value instanceof Error ? value.message : "The application form could not be loaded.")).finally(() => setLoading(false)); }, [tenantSlug]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = event.currentTarget; const data = new FormData(form); const values = Object.fromEntries(data); const customFields = Object.fromEntries(fields.map(field => [field.fieldKey, customValue(field, data)])); for (const field of fields) delete values[`custom_${field.fieldKey}`]; const response = await fetch(`/api/public/admissions/${tenantSlug}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, customFields }) }); const body = await response.json().catch(() => ({})) as { applicationNumber?: string; detail?: string }; setBusy(false); if (!response.ok) { setError(response.status === 404 ? "This school is not accepting online applications." : body.detail ?? "The application could not be submitted."); return; } setReference(body.applicationNumber ?? "Submitted"); form.reset(); }
  if (reference) return <div className="rounded-3xl bg-emerald-50 p-8"><h2 className="text-2xl font-black text-emerald-950">Application received</h2><p className="mt-3 text-emerald-900">Keep this reference: <strong>{reference}</strong></p></div>;
  if (loading) return <div className="rounded-3xl bg-white p-8 shadow-xl">Loading application form…</div>;
  return <form onSubmit={submit} className="space-y-4 rounded-3xl bg-white p-8 shadow-xl"><div className="grid gap-4 sm:grid-cols-2"><Field name="firstName" label="First name" /><Field name="lastName" label="Last name" /><Field name="dateOfBirth" label="Date of birth" type="date" /><Field name="previousSchool" label="Previous school" required={false} /><Field name="email" label="Email" type="email" required={false} /><Field name="phone" label="Phone" required={false} /></div><Field name="source" label="How did you hear about the school?" required={false} />{fields.map(field => <ConfiguredField key={field.fieldKey} field={field} />)}{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy || Boolean(error)} className="w-full rounded-xl bg-[#12372a] px-5 py-3 font-bold text-white disabled:opacity-50">{busy ? "Submitting…" : "Submit application"}</button></form>;
}
function Field({ name, label, type = "text", required = true }: { name: string; label: string; type?: string; required?: boolean }) { return <label className="block text-sm font-semibold text-slate-700">{label}<input name={name} type={type} required={required} className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-emerald-700 focus:ring-2 focus:ring-emerald-100" /></label>; }
function ConfiguredField({ field }: { field: FormField }) { const name = `custom_${field.fieldKey}`; const inputType = field.dataType === 5 ? "datetime-local" : field.dataType === 4 ? "date" : field.dataType === 7 ? "email" : field.dataType === 8 ? "tel" : field.dataType === 9 ? "url" : field.dataType === 2 || field.dataType === 3 ? "number" : "text"; return <label className="block text-sm font-semibold text-slate-700">{field.label}{field.helpText && <span className="ml-2 font-normal text-slate-500">{field.helpText}</span>}{field.dataType === 10 ? <select name={name} required={field.isRequired} defaultValue={parseDefault(field.defaultValue)} className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-3"><option value="">Select…</option>{field.options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : field.dataType === 11 ? <select name={name} required={field.isRequired} multiple className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-3">{field.options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : field.dataType === 1 ? <textarea name={name} required={field.isRequired} defaultValue={parseDefault(field.defaultValue)} className="mt-1 min-h-24 w-full rounded-xl border border-slate-300 px-4 py-3" /> : field.dataType === 6 ? <input name={name} type="checkbox" defaultChecked={parseDefault(field.defaultValue) === "true"} className="ml-3 h-4 w-4" /> : <input name={name} type={inputType} required={field.isRequired} defaultValue={parseDefault(field.defaultValue)} step={field.dataType === 3 ? "any" : undefined} className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3" />}</label>; }
function parseDefault(value?: string) { if (!value) return ""; try { const parsed = JSON.parse(value) as unknown; return typeof parsed === "string" || typeof parsed === "number" || typeof parsed === "boolean" ? String(parsed) : ""; } catch { return ""; } }
function customValue(field: FormField, data: FormData) { const name = `custom_${field.fieldKey}`; if (field.dataType === 11) return data.getAll(name); const value = data.get(name); if (field.dataType === 6) return value === "on"; if ((field.dataType === 2 || field.dataType === 3) && value !== "") return Number(value); return value === "" ? null : value; }
