"use client";
import { FormEvent, useState } from "react";

export function ApplicationForm({ tenantSlug }: { tenantSlug: string }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [reference, setReference] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); const response = await fetch(`/api/public/admissions/${tenantSlug}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const body = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setError(response.status === 404 ? "This school is not accepting online applications." : "The application could not be submitted."); return; } setReference(body.applicationNumber); form.reset(); }
  if (reference) return <div className="rounded-3xl bg-emerald-50 p-8"><h2 className="text-2xl font-black text-emerald-950">Application received</h2><p className="mt-3 text-emerald-900">Keep this reference: <strong>{reference}</strong></p></div>;
  return <form onSubmit={submit} className="space-y-4 rounded-3xl bg-white p-8 shadow-xl"><div className="grid gap-4 sm:grid-cols-2"><Field name="firstName" label="First name" /><Field name="lastName" label="Last name" /><Field name="dateOfBirth" label="Date of birth" type="date" /><Field name="previousSchool" label="Previous school" required={false} /><Field name="email" label="Email" type="email" required={false} /><Field name="phone" label="Phone" required={false} /></div><Field name="source" label="How did you hear about the school?" required={false} />{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-[#12372a] px-5 py-3 font-bold text-white disabled:opacity-50">{busy ? "Submitting…" : "Submit application"}</button></form>;
}
function Field({ name, label, type = "text", required = true }: { name: string; label: string; type?: string; required?: boolean }) { return <label className="block text-sm font-semibold text-slate-700">{label}<input name={name} type={type} required={required} className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-emerald-700 focus:ring-2 focus:ring-emerald-100" /></label>; }
