"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Applicant = { id: string; applicationNumber: string; firstName: string; lastName: string; status: number };
export function BulkApplicantProcessing() {
  const [applicants, setApplicants] = useState<Applicant[]>([]); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/backend/admissions/applicants?page=1&pageSize=100", { cache: "no-store" }); if (!response.ok) throw new Error("Applicants could not be loaded."); const body = await response.json() as { items: Applicant[] }; setApplicants(body.items); }
  useEffect(() => { void fetch("/api/backend/admissions/applicants?page=1&pageSize=100", { cache: "no-store" }).then(response => response.json()).then((body: { items: Applicant[] }) => setApplicants(body.items)).catch(() => setMessage("Applicants could not be loaded.")); }, []);
  function toggle(id: string) { setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]); }
  async function execute(action: "offer" | "reject") { if (!selected.length) return; setBusy(true); setMessage(""); const response = await fetch(`/api/backend/admissions/applicants/bulk/${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ applicantIds: selected, validForDays: 14 }) }); const result = await response.json().catch(() => null) as { succeeded?: number; failed?: number } | null; setBusy(false); if (!response.ok) { setMessage(response.status === 403 ? "You do not have permission for bulk admissions decisions." : "The batch could not be processed."); return; } setMessage(`${result?.succeeded ?? 0} succeeded; ${result?.failed ?? 0} could not be processed from their current status.`); setSelected([]); await load(); }
  return <main className="min-h-screen bg-[#f6f4ee]"><header className="bg-[#12372a] text-white"><div className="mx-auto max-w-6xl px-6 py-5"><Link href="/portal/admissions" className="font-bold text-emerald-100">← Admissions</Link></div></header><div className="mx-auto max-w-6xl px-6 py-10"><h1 className="text-4xl font-black">Bulk applicant processing</h1><p className="mt-2 text-slate-600">Select up to 100 applicants. Each result is reported independently so invalid records do not hide successful decisions.</p><div className="mt-6 flex gap-3"><button disabled={busy || !selected.length} onClick={() => void execute("offer")} className="rounded-xl bg-emerald-700 px-4 py-3 font-bold text-white disabled:opacity-50">Issue offers ({selected.length})</button><button disabled={busy || !selected.length} onClick={() => void execute("reject")} className="rounded-xl border border-red-300 bg-white px-4 py-3 font-bold text-red-800 disabled:opacity-50">Reject ({selected.length})</button></div>{message && <p role="status" className="mt-4 rounded-xl bg-white p-4">{message}</p>}<div className="mt-6 overflow-hidden rounded-3xl bg-white"><table className="w-full text-left"><thead className="bg-slate-50"><tr><th className="p-4">Select</th><th>Application</th><th>Applicant</th><th>Status</th></tr></thead><tbody>{applicants.map(applicant => <tr key={applicant.id} className="border-t"><td className="p-4"><input type="checkbox" checked={selected.includes(applicant.id)} onChange={() => toggle(applicant.id)} aria-label={`Select ${applicant.applicationNumber}`} /></td><td>{applicant.applicationNumber}</td><td>{applicant.firstName} {applicant.lastName}</td><td>{applicant.status}</td></tr>)}</tbody></table></div></div></main>;
}
