"use client";

import { useEffect, useState } from "react";
import { notify } from "@/components/app-toast";

export type GuardianStudent = { studentId: string; admissionNumber: string; firstName: string; middleName?: string | null; lastName: string; classSectionName?: string | null; relationship: number | string };
type StudentMatch = { id: string; admissionNumber: string; firstName: string; lastName: string; classLevelName: string; classSectionName: string };
const relationships = ["Mother", "Father", "Parent", "Legal guardian", "Relative", "Sponsor", "Other", "Stepmother", "Stepfather", "Grandmother", "Grandfather", "Aunt", "Uncle", "Sibling", "Foster parent", "Adoptive parent", "Caregiver"];
const field = "w-full rounded-xl border border-slate-300 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-slate-600";

async function message(response: Response) { const body = await response.json().catch(() => null) as { detail?: string; title?: string } | null; return body?.detail ?? body?.title ?? "The request could not be completed."; }

function Shell({ title, description, children, onClose }: { title: string; description: string; children: React.ReactNode; onClose: () => void }) {
  return <div className="fixed inset-0 z-[220] grid place-items-center bg-slate-950/60 p-3 backdrop-blur-sm"><div role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-white shadow-2xl"><header className="flex items-start justify-between gap-4 border-b border-slate-200 p-5 sm:p-6"><div><h2 className="text-xl font-black text-slate-950">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{description}</p></div><button type="button" onClick={onClose} aria-label="Close" className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-xl text-slate-600 hover:bg-red-50 hover:text-red-700">×</button></header>{children}</div></div>;
}

export function LinkGuardianStudentDialog({ guardianId, existingIds, onClose, onSaved }: { guardianId: string; existingIds: string[]; onClose: () => void; onSaved: () => void }) {
  const [query, setQuery] = useState(""); const [matches, setMatches] = useState<StudentMatch[]>([]); const [selected, setSelected] = useState<StudentMatch | null>(null); const [relationship, setRelationship] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (query.trim().length < 2) { setMatches([]); return; } const controller = new AbortController(); const timer = window.setTimeout(() => void fetch(`/api/backend/guardians/student-search?query=${encodeURIComponent(query.trim())}`, { signal: controller.signal }).then(async response => { if (!response.ok) throw new Error(await message(response)); return response.json() as Promise<StudentMatch[]>; }).then(rows => setMatches(rows.filter(row => !existingIds.includes(row.id)))).catch(reason => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "Search failed."); }), 250); return () => { window.clearTimeout(timer); controller.abort(); }; }, [query, existingIds]);
  async function save() { if (!selected || relationship === "") { setError("Select a student and relationship."); return; } setBusy(true); setError(""); try { const response = await fetch(`/api/backend/students/${selected.id}/guardians`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ guardianId, relationship: Number(relationship), isPrimary: false, isEmergencyContact: false, mayCollect: false }) }); if (!response.ok) throw new Error(await message(response)); notify({ title: "Student linked", message: `${selected.firstName} ${selected.lastName} is now linked to this guardian.` }); onSaved(); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Student could not be linked."); } finally { setBusy(false); } }
  return <Shell title="Link a student" description="Search within the active campus, confirm the student, then choose this guardian’s relationship." onClose={onClose}><div className="space-y-4 p-5 sm:p-6">{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<label className="block text-sm font-bold text-slate-700">Search student<input value={query} onChange={event => { setQuery(event.target.value); setSelected(null); }} placeholder="Name or admission number" className={`${field} mt-1.5`} /></label>{matches.length > 0 && <div className="max-h-48 space-y-1 overflow-y-auto rounded-xl border border-slate-200 p-1.5">{matches.map(student => <button key={student.id} type="button" onClick={() => setSelected(student)} className={`block w-full rounded-lg p-3 text-left text-sm ${selected?.id === student.id ? "bg-emerald-50 ring-1 ring-emerald-300" : "hover:bg-slate-50"}`}><strong>{student.firstName} {student.lastName}</strong><span className="mt-0.5 block text-xs text-slate-500">{student.admissionNumber} · {student.classSectionName}</span></button>)}</div>}<label className="block text-sm font-bold text-slate-700">Relationship<select value={relationship} onChange={event => setRelationship(event.target.value)} className={`${field} mt-1.5`}><option value="">Select relationship</option>{relationships.map((name, index) => <option key={name} value={index}>{name}</option>)}</select></label><footer className="flex justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="rounded-xl bg-red-50 px-4 py-2.5 text-sm font-bold text-red-700 hover:bg-red-100">Cancel</button><button type="button" disabled={busy} onClick={() => void save()} className="tenant-primary-bg rounded-xl px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy ? "Linking…" : "Link student"}</button></footer></div></Shell>;
}

export function GuardianRelationshipDialog({ guardianId, students, onClose, onSaved }: { guardianId: string; students: GuardianStudent[]; onClose: () => void; onSaved: () => void }) {
  const [busyId, setBusyId] = useState(""); const [error, setError] = useState("");
  async function update(studentId: string, relationship: number) { setBusyId(studentId); setError(""); try { const response = await fetch(`/api/backend/guardians/${guardianId}/student-links/${studentId}/relationship`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ relationship }) }); if (!response.ok) throw new Error(await message(response)); notify({ title: "Relationship updated", message: "The guardian relationship was saved." }); onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Relationship could not be updated."); } finally { setBusyId(""); } }
  return <Shell title="Change guardian relationship" description="Relationships are managed separately for each linked student." onClose={onClose}><div className="space-y-3 p-5 sm:p-6">{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}{students.length === 0 ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">No students are linked to this guardian yet.</p> : students.map(student => <div key={student.studentId} className="rounded-2xl border border-slate-200 p-4"><p className="font-black text-slate-950">{student.firstName} {student.lastName}</p><p className="mb-3 text-xs text-slate-500">{student.admissionNumber} · {student.classSectionName ?? "No active class"}</p><select disabled={busyId === student.studentId} value={typeof student.relationship === "number" ? student.relationship : relationships.findIndex(name => name.replace(" ", "").toLowerCase() === String(student.relationship).toLowerCase())} onChange={event => void update(student.studentId, Number(event.target.value))} className={field}>{relationships.map((name, index) => <option key={name} value={index}>{name}</option>)}</select></div>)}<div className="flex justify-end pt-2"><button type="button" onClick={onClose} className="rounded-xl bg-red-50 px-4 py-2.5 text-sm font-bold text-red-700 hover:bg-red-100">Close</button></div></div></Shell>;
}

export function GuardianStatusDialog({ count, initialStatus, onClose, onSave }: { count: number; initialStatus?: number; onClose: () => void; onSave: (status: number) => Promise<void> }) {
  const [status, setStatus] = useState(String(initialStatus ?? 0)); const [busy, setBusy] = useState(false);
  async function save() { setBusy(true); try { await onSave(Number(status)); onClose(); } finally { setBusy(false); } }
  return <Shell title="Update guardian status" description={`Change the lifecycle status for ${count} selected guardian${count === 1 ? "" : "s"}.`} onClose={onClose}><div className="space-y-5 p-5 sm:p-6"><label className="block text-sm font-bold text-slate-700">Status<select value={status} onChange={event => setStatus(event.target.value)} className={`${field} mt-1.5`}><option value="0">Active</option><option value="1">Inactive</option><option value="2">Suspended</option></select></label><footer className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl bg-red-50 px-4 py-2.5 text-sm font-bold text-red-700">Cancel</button><button type="button" disabled={busy} onClick={() => void save()} className="tenant-primary-bg rounded-xl px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy ? "Updating…" : "Update status"}</button></footer></div></Shell>;
}
