"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type RecordValue = string | number | boolean | null;
type ResourceRecord = Record<string, RecordValue>;
const noFields: CreateField[] = [];
type CreateField = { name: string; label: string; type?: "text" | "email" | "date" | "number" | "select" | "file"; required?: boolean; numeric?: boolean; options?: { value: string; label: string }[]; optionsEndpoint?: string; optionsCollectionKey?: string; optionLabelKey?: string };
export type CreateConfig = { endpoint: string; title: string; method?: "POST" | "PUT"; fields: CreateField[] };
export type RecordActionConfig = { endpoint: string; title: string; method?: "POST" | "PUT" | "DELETE"; fields?: CreateField[]; payload?: Record<string, string | number | boolean>; itemIdField?: string; documentUpload?: boolean; href?: string };
export type ResourcePageProps = { title: string; description: string; endpoint: string; fields: { key: string; label: string }[]; collectionKey?: string; emptyMessage: string; create?: CreateConfig; creates?: CreateConfig[]; actions?: RecordActionConfig[]; detailPath?: string };

export function ResourcePage({ title, description, endpoint, fields, collectionKey, emptyMessage, create, creates = [], actions = [], detailPath }: ResourcePageProps) {
  const router = useRouter();
  const [items, setItems] = useState<ResourceRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [revision, setRevision] = useState(0);
  const createForms = create ? [create, ...creates] : creates;

  useEffect(() => {
    void fetch(`/api/backend/${endpoint}`, { cache: "no-store" }).then(async response => {
      if (response.status === 401) { router.replace("/login"); return; }
      if (response.status === 403) { setError("This module is not permitted or subscribed for this workspace."); return; }
      if (!response.ok) { setError("The module data could not be loaded."); return; }
      const body = await response.json(); const source = collectionKey ? body[collectionKey] : body.items ?? body;
      setItems(Array.isArray(source) ? source : source ? [source] : []); setError("");
    }).catch(() => setError("The service is temporarily unavailable.")).finally(() => setLoading(false));
  }, [collectionKey, endpoint, revision, router]);

  return <main className="min-h-screen bg-[#f6f4ee]"><header className="bg-[#12372a] text-white"><div className="mx-auto max-w-7xl px-6 py-5"><Link href="/portal" className="text-sm font-bold text-emerald-100">← Workspace</Link></div></header><div className="mx-auto max-w-7xl px-6 py-10"><h1 className="text-4xl font-black">{title}</h1><p className="mt-2 text-slate-600">{description}</p>{createForms.length > 0 && <div className="mt-8 grid gap-4 lg:grid-cols-2">{createForms.map(form => <CreateRecord key={`${form.method ?? "POST"}:${form.endpoint}`} config={form} onCreated={() => setRevision(value => value + 1)} />)}</div>}{loading ? <Panel>Loading records…</Panel> : error ? <Panel>{error}</Panel> : items.length === 0 ? <Panel>{emptyMessage}</Panel> : <div className="mt-8 overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{fields.map(field => <th key={field.key} className="px-5 py-4">{field.label}</th>)}{actions.length > 0 && <th className="px-5 py-4">Actions</th>}</tr></thead><tbody>{items.map((item, index) => <tr key={String(item.id ?? index)} className="border-t border-slate-100">{fields.map((field, fieldIndex) => <td key={field.key} className="px-5 py-4 text-sm">{detailPath && fieldIndex===0 ? <Link className="font-bold text-emerald-800 underline" href={`${detailPath}/${item.id}`}>{format(item[field.key])}</Link> : format(item[field.key])}</td>)}{actions.length > 0 && <td className="px-5 py-4"><div className="flex flex-wrap gap-2">{actions.map(action => <RecordAction key={action.title} item={item} config={action} onCompleted={() => setRevision(value => value + 1)} />)}</div></td>}</tr>)}</tbody></table></div></div>}</div></main>;
}

function format(value: RecordValue | undefined) { if (value === null || value === undefined || value === "") return "—"; if (typeof value === "boolean") return value ? "Yes" : "No"; return String(value); }
function Panel({ children }: { children: React.ReactNode }) { return <div className="mt-8 rounded-3xl border border-slate-200 bg-white p-8 text-slate-600">{children}</div>; }

function CreateRecord({ config, onCreated }: { config: CreateConfig; onCreated: () => void }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [remoteOptions, setRemoteOptions] = useState<Record<string, { value: string; label: string }[]>>({});
  useEffect(() => { for (const field of config.fields.filter(item => item.optionsEndpoint)) void fetch(`/api/backend/${field.optionsEndpoint}`).then(response => response.json()).then(body => { const source = field.optionsCollectionKey ? body[field.optionsCollectionKey] : body.items ?? body; if (!Array.isArray(source)) return; setRemoteOptions(current => ({ ...current, [field.name]: source.map((item: ResourceRecord) => ({ value: String(item.id), label: String(item[field.optionLabelKey ?? "name"]) })) })); }); }, [config.fields]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = event.currentTarget; const data = new FormData(form); const payload = Object.fromEntries(config.fields.map(field => { const value = data.get(field.name); if (value === "" && field.required === false) return [field.name, null]; if (field.numeric) return [field.name, Number(value)]; if (field.type === "select" && (value === "true" || value === "false")) return [field.name, value === "true"]; return [field.name, value]; })); const response = await fetch(`/api/backend/${config.endpoint}`, { method: config.method ?? "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); setBusy(false); if (!response.ok) { setError(response.status === 403 ? "You do not have permission to create this record." : "The record could not be created. Check the values and try again."); return; } form.reset(); setOpen(false); onCreated(); }
  return <section className="rounded-3xl bg-white p-6 shadow-sm"><button type="button" onClick={() => setOpen(value => !value)} className="rounded-xl bg-[#12372a] px-5 py-3 font-bold text-white">{open ? "Cancel" : config.title}</button>{open && <form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2">{config.fields.map(field => <label key={field.name} className="text-sm font-semibold text-slate-700">{field.label}{field.type === "select" ? <select name={field.name} required={field.required !== false} className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-3"><option value="">Select…</option>{[...(field.options ?? []), ...(remoteOptions[field.name] ?? [])].map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input name={field.name} type={field.type ?? "text"} required={field.required !== false} className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3" />}</label>)}{error && <p role="alert" className="sm:col-span-2 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="sm:col-span-2 rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white disabled:opacity-50">{busy ? "Saving…" : "Save"}</button></form>}</section>;
}

function RecordAction({ item, config, onCompleted }: { item: ResourceRecord; config: RecordActionConfig; onCompleted: () => void }) {
  const fields = config.fields ?? noFields;
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [remoteOptions, setRemoteOptions] = useState<Record<string, { value: string; label: string }[]>>({});
  useEffect(() => { for (const field of fields.filter(value => value.optionsEndpoint)) void fetch(`/api/backend/${field.optionsEndpoint}`).then(response => response.json()).then(body => { const source = field.optionsCollectionKey ? body[field.optionsCollectionKey] : body.items ?? body; if (!Array.isArray(source)) return; setRemoteOptions(current => ({ ...current, [field.name]: source.map((value: ResourceRecord) => ({ value: String(value.id), label: String(value[field.optionLabelKey ?? "name"]) })) })); }); }, [fields]);
  const endpoint = config.endpoint.replace("{id}", String(item.id));
  if(config.href)return <Link href={config.href.replace("{id}",String(item.id))} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold">Open</Link>;
  async function execute(payload?: Record<string, unknown>) { setBusy(true); setError(""); const response = await fetch(`/api/backend/${endpoint}`, { method: config.method ?? "POST", headers: payload ? { "Content-Type": "application/json" } : undefined, body: payload ? JSON.stringify(payload) : undefined }); setBusy(false); if (!response.ok) { setError(response.status === 403 ? "You do not have permission for this action." : "The action could not be completed. Check the values and current status."); return; } setOpen(false); onCompleted(); }
  function fixedPayload() { return { ...(config.payload ?? {}), ...(config.itemIdField ? { [config.itemIdField]: item.id } : {}) }; }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if(config.documentUpload){const file=data.get("file");if(!(file instanceof File)||file.size===0){setError("Choose a document to upload.");return;}setBusy(true);setError("");try{const begin=await fetch(`/api/backend/${endpoint}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileName:file.name,contentType:file.type,sizeBytes:file.size,category:data.get("category")})});if(!begin.ok)throw new Error("The upload could not be started.");const upload=await begin.json() as {fileId:string;uploadUrl:string};const stored=await fetch(upload.uploadUrl,{method:"PUT",headers:{"Content-Type":file.type},body:file});if(!stored.ok)throw new Error("The document could not be stored.");const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());const checksum=Array.from(new Uint8Array(digest),value=>value.toString(16).padStart(2,"0")).join("");const complete=await fetch(`/api/backend/documents/${upload.fileId}/complete`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({checksum})});if(!complete.ok)throw new Error("The upload could not be verified.");setOpen(false);onCompleted();}catch(error){setError(error instanceof Error?error.message:"The upload failed.");}finally{setBusy(false);}return;} const payload = { ...fixedPayload(), ...Object.fromEntries(fields.map(field => { const value = data.get(field.name); if (value === "" && field.required === false) return [field.name, null]; if (field.numeric) return [field.name, Number(value)]; if (field.type === "select" && (value === "true" || value === "false")) return [field.name, value === "true"]; return [field.name, value]; })) }; await execute(payload); }
  if (fields.length === 0) return <div><button type="button" disabled={busy} onClick={() => setOpen(value => !value)} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold disabled:opacity-50">{config.title}</button>{open && <div className="mt-3 min-w-60 rounded-xl border border-slate-200 bg-slate-50 p-3"><p className="text-xs text-slate-600">Confirm this action. It may change the record&apos;s active status.</p><button type="button" disabled={busy} onClick={() => void execute(fixedPayload())} className="mt-3 w-full rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{busy ? "Working…" : "Confirm"}</button></div>}{error && <p role="alert" className="mt-2 max-w-xs text-xs text-red-700">{error}</p>}</div>;
  return <div><button type="button" onClick={() => setOpen(value => !value)} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold">{config.title}</button>{open && <form onSubmit={submit} className="mt-3 min-w-72 space-y-3 rounded-xl border border-slate-200 bg-slate-50 p-3">{fields.map(field => <label key={field.name} className="block text-xs font-semibold">{field.label}{field.type === "select" ? <select name={field.name} required={field.required !== false} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2"><option value="">Select…</option>{[...(field.options ?? []), ...(remoteOptions[field.name] ?? [])].map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input name={field.name} type={field.type ?? "text"} required={field.required !== false} accept={field.type==="file"?"application/pdf,image/jpeg,image/png":undefined} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" />}</label>)}{error && <p role="alert" className="text-xs text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{busy ? "Working…" : "Confirm"}</button></form>}</div>;
}
