"use client";

import Image from "next/image";
import { FormEvent, useEffect, useId, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { nigeriaLocations, nigeriaStates } from "@/lib/nigeria-locations";

type Profile = { displayName: string; schoolSlug: string; schoolType: string; legalName?: string; tagline?: string; email?: string; phone?: string; websiteUrl?: string; address?: string; state?: string; localGovernment?: string; countryCode: string; timeZone: string; currencyCode: string; dateFormat: string; timeFormat: string; customDomain?: string; logoFileId?: string; principalSignatureFileId?: string; primaryColor?: string; secondaryColor?: string; logoUrl?: string; principalSignatureUrl?: string; brandingScope?: string };
type Campus = { id: string; name: string; code: string; isMainCampus: boolean; isActive: boolean };
type Access = { tenantId: string; campusId?: string | null; campusName?: string | null; permissions: string[] };
type BrandingResponse = { scope: string; primaryColor?: string; secondaryColor?: string; logoFileId?: string; principalSignatureFileId?: string; logoUrl?: string };
const blankProfile: Profile = { displayName: "", schoolSlug: "", schoolType: "Not specified", countryCode: "NG", timeZone: "Africa/Lagos", currencyCode: "NGN", dateFormat: "dd/MM/yyyy", timeFormat: "HH:mm", primaryColor: "#12372A", secondaryColor: "#10B981" };

export function SchoolOnboarding() {
  const router = useRouter();
  const [profile, setProfile] = useState<Profile>(blankProfile); const [campuses, setCampuses] = useState<Campus[]>([]); const [access, setAccess] = useState<Access | null>(null);
  const savedBranding = useRef<Pick<Profile, "primaryColor" | "secondaryColor" | "logoUrl">>(blankProfile);
  const [step, setStep] = useState(0); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const canManage = access?.permissions.includes("Schools.Manage") === true;
  const completed = useMemo(() => [Boolean(profile.displayName && profile.legalName && profile.email && profile.address && profile.state && profile.localGovernment), Boolean(profile.primaryColor && profile.secondaryColor), campuses.some(campus => campus.isActive)], [profile, campuses]);

  useEffect(() => { Promise.all([fetch("/api/auth/session", { cache: "no-store" }), fetch("/api/backend/schools/current", { cache: "no-store" }), fetch("/api/backend/schools/campuses", { cache: "no-store" }), fetch("/api/backend/schools/branding", { cache: "no-store" })]).then(async ([sessionResponse, profileResponse, campusResponse, brandingResponse]) => {
    if (sessionResponse.status === 401) { router.replace("/login"); return; }
    if (!sessionResponse.ok || !campusResponse.ok) throw new Error("School configuration could not be loaded.");
    const session = await sessionResponse.json() as { access?: Access }; setAccess(session.access ?? null);
    if (profileResponse.ok) { const loaded = await profileResponse.json() as Profile; const branding: Partial<BrandingResponse> = brandingResponse.ok ? await brandingResponse.json() as BrandingResponse : {}; const hydrated = { ...blankProfile, ...loaded, ...branding, brandingScope: branding.scope, legalName: loaded.legalName || loaded.displayName, dateFormat: loaded.dateFormat || blankProfile.dateFormat, timeFormat: loaded.timeFormat || blankProfile.timeFormat }; savedBranding.current = hydrated; setProfile(hydrated); } else if (profileResponse.status !== 404) throw new Error("School profile could not be loaded.");
    setCampuses(await campusResponse.json() as Campus[]);
  }).catch(error => setMessage(error instanceof Error ? error.message : "School configuration could not be loaded.")).finally(() => setLoading(false)); }, [router]);
  useEffect(() => () => announceBranding(savedBranding.current), []);

  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await fetch("/api/backend/schools/current", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); if (!response.ok) throw new Error(response.status === 403 ? "You do not have permission to configure this school." : "Check the profile details and try again."); setMessage("School profile saved."); setStep(1); } catch (error) { setMessage(error instanceof Error ? error.message : "Profile could not be saved."); } finally { setBusy(false); } }
  async function saveBranding(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); try { const data = new FormData(event.currentTarget); const logo = data.get("logo"); const signature = data.get("principalSignature"); let logoFileId = profile.logoFileId; let principalSignatureFileId = profile.principalSignatureFileId; if (logo instanceof File && logo.size > 0) logoFileId = await uploadBrandAsset(logo, "branding-logo", "School logo"); if (signature instanceof File && signature.size > 0) principalSignatureFileId = await uploadBrandAsset(signature, "principal-signature", "Principal signature"); const response = await fetch("/api/backend/schools/branding", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ displayName: profile.displayName, scope: access?.campusId ? "Campus" : "Tenant", primaryColor: profile.primaryColor, secondaryColor: profile.secondaryColor, logoFileId, principalSignatureFileId }) }); if (!response.ok) throw new Error(response.status === 403 ? "You do not have permission to update branding." : "Branding could not be saved."); const refreshedResponse = await fetch("/api/backend/schools/branding", { cache: "no-store" }); const branding = refreshedResponse.ok ? await refreshedResponse.json() as { scope: string; primaryColor?: string; secondaryColor?: string; logoFileId?: string; principalSignatureFileId?: string; logoUrl?: string; principalSignatureUrl?: string } : { scope: access?.campusId ? "Campus" : "Tenant", primaryColor: profile.primaryColor, secondaryColor: profile.secondaryColor, logoFileId, principalSignatureFileId }; const refreshed = { ...profile, ...branding, brandingScope: branding.scope }; savedBranding.current = refreshed; setProfile(refreshed); announceBranding(refreshed); setMessage(access?.campusId ? `Branding override saved for ${access.campusName ?? "this campus"}.` : "School-wide branding defaults saved."); setStep(2); } catch (error) { setMessage(error instanceof Error ? error.message : "Branding could not be saved."); } finally { setBusy(false); } }
  async function uploadBrandAsset(file: File, category: string, label: string) { if (!access) throw new Error("Your tenant session is unavailable."); if (!["image/png", "image/jpeg"].includes(file.type) || file.size > 2 * 1024 * 1024) throw new Error(`${label} must be a PNG or JPEG no larger than 2 MB.`); const begin = await fetch("/api/backend/foundation/files", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fileName: file.name, contentType: file.type, sizeBytes: file.size, category, entityType: "SchoolProfile", entityId: access.campusId ?? access.tenantId }) }); if (!begin.ok) throw new Error(`${label} upload could not be started.`); const upload = await begin.json() as { fileId: string }; const stored = await fetch(`/api/backend/foundation/files/${upload.fileId}/content`, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!stored.ok) throw new Error(`${label} could not be stored.`); const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); const checksum = Array.from(new Uint8Array(digest), value => value.toString(16).padStart(2, "0")).join(""); const complete = await fetch(`/api/backend/foundation/files/${upload.fileId}/complete`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ checksum }) }); if (!complete.ok) throw new Error(`${label} upload could not be verified.`); return upload.fileId; }
  async function addCampus(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = event.currentTarget; const data = new FormData(form); try { const response = await fetch("/api/backend/schools/campuses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), isMainCampus: data.get("isMainCampus") === "yes" }) }); if (!response.ok) throw new Error(response.status === 403 ? "You do not have permission to add campuses." : "Campus details could not be saved."); const refreshed = await fetch("/api/backend/schools/campuses", { cache: "no-store" }); setCampuses(await refreshed.json() as Campus[]); form.reset(); setMessage("Campus added with a system-generated code."); } catch (error) { setMessage(error instanceof Error ? error.message : "Campus could not be saved."); } finally { setBusy(false); } }
  async function clearCampusBranding() { setBusy(true); setMessage(""); try { const response = await fetch("/api/backend/schools/branding", { method: "DELETE" }); if (!response.ok) throw new Error("The campus branding override could not be removed."); const refreshedResponse = await fetch("/api/backend/schools/branding", { cache: "no-store" }); if (!refreshedResponse.ok) throw new Error("The school-wide branding could not be loaded."); const branding = await refreshedResponse.json() as BrandingResponse; const refreshed = { ...profile, ...branding, brandingScope: branding.scope }; savedBranding.current = refreshed; setProfile(refreshed); announceBranding(refreshed); setMessage(`${access?.campusName ?? "Campus"} now inherits the school-wide branding.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Campus branding could not be reset."); } finally { setBusy(false); } }

  if (loading) return <Panel>Loading school setup…</Panel>;
  return <section className="w-full"><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">School onboarding</p><h1 className="mt-2 text-3xl font-black text-slate-950 sm:text-4xl">Configure your school</h1><p className="mt-2 text-slate-600">Complete the profile, branding and campus setup used throughout GiddyEdu.</p><ol className="mt-8 grid gap-3 sm:grid-cols-3">{["School profile", "Branding", "Campuses"].map((label, index) => <li key={label}><button type="button" onClick={() => { if (step === 1 && index !== 1) announceBranding(savedBranding.current); setStep(index); }} className={`w-full rounded-2xl border p-4 text-left font-bold transition ${step === index ? "border-emerald-700 bg-emerald-50 text-emerald-950" : "border-slate-200 bg-white hover:border-emerald-300"}`}><span className="mr-2">{completed[index] ? "✓" : index + 1}</span>{label}</button></li>)}</ol>{!canManage && <p role="alert" className="mt-6 rounded-2xl bg-amber-50 p-4 text-amber-900">You can view this setup, but Schools.Manage permission is required to change it.</p>}{step === 0 && <ProfileForm profile={profile} setProfile={setProfile} submit={saveProfile} disabled={!canManage || busy} />}{step === 1 && <BrandingForm profile={profile} access={access} setProfile={setProfile} submit={saveBranding} resetCampusBranding={clearCampusBranding} disabled={!canManage || busy} />}{step === 2 && <CampusForm campuses={campuses} submit={addCampus} disabled={!canManage || busy} />}{message && <p role="status" className="mt-5 rounded-2xl bg-white p-4 text-sm text-slate-700">{message}</p>}</section>;
}

function ProfileForm({ profile, setProfile, submit, disabled }: { profile: Profile; setProfile: (value: Profile) => void; submit: (event: FormEvent<HTMLFormElement>) => void; disabled: boolean }) {
  const field = (key: keyof Profile) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setProfile({ ...profile, [key]: event.target.value });
  const localGovernments = profile.state && profile.state in nigeriaLocations ? [...nigeriaLocations[profile.state as keyof typeof nigeriaLocations]] : [];
  const sectionClass = "rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7";
  return <form onSubmit={submit} className="mt-8 space-y-5">
    <section className={sectionClass}>
      <SectionHeading eyebrow="School identity" title="Basic details" description="The official details used across records, communications and reports." />
      <div className="mt-6 grid gap-5 sm:grid-cols-2">
        <Input label="School display name" value={profile.displayName} onChange={field("displayName")} required helper="The familiar name shown throughout the portal, mobile apps and school communications." />
        <Input label="School registered / legal name" value={profile.legalName ?? profile.displayName} onChange={field("legalName")} required helper="The official name used for formal records, invoices and regulatory documents. It may be the same as the display name." />
        <label className="text-sm font-semibold">School type<select value={profile.schoolType} onChange={field("schoolType")} required className="field-control"><option value="Not specified" disabled>Select school type</option>{["Nursery", "Primary", "Secondary", "Primary and Secondary", "Nursery, Primary and Secondary"].map(value => <option key={value}>{value}</option>)}</select></label>
        <Input label="School tagline / motto" value={profile.tagline ?? ""} onChange={field("tagline")} maxLength={160} placeholder="Inspiring every learner to thrive" />
      </div>
    </section>
    <section className={sectionClass}>
      <SectionHeading eyebrow="How families reach you" title="Contact and location" description="Keep these details accurate for school correspondence and location-aware services." />
      <div className="mt-6 grid gap-5 sm:grid-cols-2">
        <Input label="School email" type="email" value={profile.email ?? ""} onChange={field("email")} required />
        <Input label="School phone" type="tel" inputMode="numeric" autoComplete="tel" value={profile.phone ?? ""} onChange={event => setProfile({ ...profile, phone: event.target.value.replace(/\D/g, "").slice(0, 11) })} placeholder="09096735531" minLength={11} maxLength={11} pattern="[0-9]{11}" helper="Enter exactly 11 digits without spaces or symbols." />
        <Input label="School website" type="url" value={profile.websiteUrl ?? ""} onChange={field("websiteUrl")} placeholder="https://www.yourschool.edu.ng" />
        <div className="hidden sm:block" />
        <SearchableSelect label="State" value={profile.state ?? ""} options={nigeriaStates} placeholder="Search Nigerian states" required onChange={state => setProfile({ ...profile, state, localGovernment: nigeriaLocations[state as keyof typeof nigeriaLocations]?.includes(profile.localGovernment as never) ? profile.localGovernment : "" })} />
        <SearchableSelect label="Local government area" value={profile.localGovernment ?? ""} options={localGovernments} placeholder={profile.state ? "Search local government areas" : "Select a state first"} required disabled={!profile.state} onChange={localGovernment => setProfile({ ...profile, localGovernment })} />
        <label className="text-sm font-semibold sm:col-span-2">Full school address<textarea value={profile.address ?? ""} onChange={field("address")} required placeholder="Street, town or district, and nearest landmark" className="field-control min-h-28 resize-y" /></label>
      </div>
    </section>
    <section className={sectionClass}>
      <SectionHeading eyebrow="Local preferences" title="Regional settings" description="These defaults control how dates, times and amounts appear across your workspace." />
      <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <ReadOnlyField label="Country" value="Nigeria" />
        <label className="text-sm font-semibold">Time zone<select value={profile.timeZone} onChange={field("timeZone")} required className="field-control"><option value="Africa/Lagos">West Africa Time (Lagos)</option></select></label>
        <label className="text-sm font-semibold">Currency<select value={profile.currencyCode} onChange={field("currencyCode")} required className="field-control"><option value="NGN">Nigerian Naira (NGN)</option></select></label>
        <label className="text-sm font-semibold">Country code<select value={profile.countryCode} onChange={field("countryCode")} required className="field-control"><option value="NG">NG · Nigeria</option></select></label>
        <label className="text-sm font-semibold">Date format<select value={profile.dateFormat} onChange={field("dateFormat")} required className="field-control"><option value="dd/MM/yyyy">DD/MM/YYYY</option><option value="MM/dd/yyyy">MM/DD/YYYY</option><option value="yyyy-MM-dd">YYYY-MM-DD</option></select></label>
        <label className="text-sm font-semibold">Time format<select value={profile.timeFormat} onChange={field("timeFormat")} required className="field-control"><option value="HH:mm">24-hour (14:30)</option><option value="hh:mm tt">12-hour (02:30 PM)</option></select></label>
      </div>
    </section>
    <section className={sectionClass}>
      <SectionHeading eyebrow="Your web address" title="Domain settings" description="Use the included GiddyEdu address now, and connect a branded domain when you are ready." />
      <div className="mt-6 grid gap-5 lg:grid-cols-2">
        <label className="text-sm font-semibold">Default GiddyEdu domain<div className="mt-1 flex overflow-hidden rounded-xl border border-slate-300 bg-white focus-within:border-emerald-600 focus-within:ring-2 focus-within:ring-emerald-100"><input value={profile.schoolSlug} onChange={event => setProfile({ ...profile, schoolSlug: slugify(event.target.value) })} required minLength={3} maxLength={100} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" className="min-w-0 flex-1 px-4 py-3 outline-none" /><span className="flex items-center border-l border-slate-200 bg-slate-50 px-3 text-sm text-slate-500">.giddyedu.com</span></div><span className="mt-2 block text-xs text-slate-500">Included with your workspace. Changes must remain unique.</span></label>
        <Input label="Custom domain (optional)" value={profile.customDomain ?? ""} onChange={field("customDomain")} placeholder="portal.yourschool.edu.ng" helper="Enter only the domain name. DNS verification will be completed before it becomes active." />
      </div>
    </section>
    <div className="flex justify-end"><Submit disabled={disabled} label="Save profile and continue" /></div>
  </form>;
}

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">{eyebrow}</p><h2 className="mt-1 text-xl font-black text-slate-950">{title}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">{description}</p></div>; }
function ReadOnlyField({ label, value }: { label: string; value: string }) { return <label className="text-sm font-semibold">{label}<span className="field-control block bg-slate-50 text-slate-600">{value}</span></label>; }
function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/-+/g, "-").replace(/^-/, ""); }

function SearchableSelect({ label, value, options, placeholder, required, disabled, onChange }: { label: string; value: string; options: readonly string[]; placeholder: string; required?: boolean; disabled?: boolean; onChange: (value: string) => void }) {
  const id = useId(); const [open, setOpen] = useState(false); const [query, setQuery] = useState("");
  const visibleValue = open ? query : value;
  const filtered = options.filter(option => option.toLowerCase().includes(visibleValue.toLowerCase())).slice(0, 50);
  return <label htmlFor={id} className="relative text-sm font-semibold">{label}
    <input id={id} role="combobox" aria-expanded={open} aria-controls={`${id}-options`} autoComplete="off" value={visibleValue} placeholder={placeholder} disabled={disabled} required={required} onFocus={() => { setQuery(value); setOpen(true); }} onBlur={() => window.setTimeout(() => setOpen(false), 120)} onChange={event => { setQuery(event.target.value); onChange(""); setOpen(true); }} className="field-control" />
    {open && !disabled && <ul id={`${id}-options`} role="listbox" className="absolute z-20 mt-1 max-h-60 w-full overflow-auto rounded-xl border border-slate-200 bg-white p-1 shadow-xl">{filtered.length ? filtered.map(option => <li key={option}><button type="button" role="option" aria-selected={value === option} onMouseDown={event => event.preventDefault()} onClick={() => { onChange(option); setQuery(option); setOpen(false); }} className="w-full rounded-lg px-3 py-2 text-left text-sm font-medium hover:bg-emerald-50 hover:text-emerald-900">{option}</button></li>) : <li className="px-3 py-3 text-sm font-normal text-slate-500">No matching option</li>}</ul>}
  </label>;
}
function BrandingForm({ profile, access, setProfile, submit, resetCampusBranding, disabled }: { profile: Profile; access: Access | null; setProfile: (value: Profile) => void; submit: (event: FormEvent<HTMLFormElement>) => void; resetCampusBranding: () => Promise<void>; disabled: boolean }) {
  const updateColour = (key: "primaryColor" | "secondaryColor", colour: string) => { const updated = { ...profile, [key]: colour.toUpperCase() }; setProfile(updated); if (isHexColour(updated.primaryColor) && isHexColour(updated.secondaryColor)) announceBranding(updated); };
  return <form onSubmit={submit} className="mt-8 space-y-5">{access?.campusId && <div className="flex flex-col gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black">Editing {access.campusName ?? "campus"} branding</p><p className="mt-1 text-blue-900/70">Saving creates an override for this campus only. Other campuses keep their own branding or inherit the school-wide default.</p></div>{profile.brandingScope === "Campus" && <button type="button" disabled={disabled} onClick={() => void resetCampusBranding()} className="shrink-0 rounded-xl border border-blue-300 bg-white px-4 py-2 font-bold text-blue-800 hover:bg-blue-100 disabled:opacity-50">Use school default</button>}</div>}
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><SectionHeading eyebrow="Colour system" title="Choose your school colours" description="Changes preview instantly across the dashboard. They become permanent only after you save branding." /><div className="mt-6 grid gap-5 lg:grid-cols-2"><HexColourField label="Primary colour" description="Used for the sidebar, major surfaces and primary actions." value={profile.primaryColor ?? "#12372A"} onChange={value => updateColour("primaryColor", value)} /><HexColourField label="Secondary colour" description="Used for active states, highlights and supporting accents." value={profile.secondaryColor ?? "#10B981"} onChange={value => updateColour("secondaryColor", value)} /></div></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><SectionHeading eyebrow="School assets" title="Logo and authorised signature" description="Upload clean, high-resolution assets that remain consistent across the portal and official school documents." /><div className="mt-6 grid gap-5 lg:grid-cols-2"><AssetUpload name="logo" title="Square school logo" detail="PNG or JPEG · maximum 2 MB · recommended 800 × 800 px. Used beside the school name, on ID cards and certificates." currentUrl={profile.logoUrl} currentLabel={profile.logoFileId ? "Current school logo" : undefined} square /><AssetUpload name="principalSignature" title="Principal signature" detail="PNG or JPEG · maximum 2 MB · use a transparent or white background. Used on authorised certificates and letters." currentUrl={profile.principalSignatureUrl} currentLabel={profile.principalSignatureFileId ? "Current principal signature" : undefined} /></div></section>
    <section className="overflow-hidden rounded-3xl text-white shadow-sm" style={{ background: `linear-gradient(135deg, ${profile.primaryColor}, ${profile.secondaryColor})` }}><div className="p-7 sm:p-9"><p className="text-xs font-black uppercase tracking-[.18em] text-white/70">Live brand preview</p><div className="mt-5 flex items-center gap-4">{profile.logoUrl ? <Image unoptimized src={profile.logoUrl} width={64} height={64} alt="" className="size-16 rounded-2xl bg-white object-contain p-2" /> : <span className="grid size-16 place-items-center rounded-2xl bg-white/15 text-2xl font-black">{profile.displayName.slice(0, 1) || "S"}</span>}<div><p className="text-2xl font-black">{profile.displayName || "Your school"}</p><p className="mt-1 text-sm text-white/70">A preview of your branded workspace</p></div></div></div></section>
    <div className="flex justify-end"><Submit disabled={disabled} label="Save branding and continue" /></div>
  </form>;
}

function HexColourField({ label, description, value, onChange }: { label: string; description: string; value: string; onChange: (value: string) => void }) { const validValue = isHexColour(value) ? value : "#000000"; return <label className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><span className="font-black text-slate-900">{label}</span><span className="mt-1 block text-xs font-normal leading-5 text-slate-500">{description}</span><span className="mt-4 flex items-center gap-3"><input type="color" value={validValue} onChange={event => onChange(event.target.value)} className="h-12 w-14 shrink-0 cursor-pointer rounded-xl border border-slate-300 bg-white p-1" aria-label={`${label} picker`} /><input value={value} onChange={event => onChange(event.target.value.slice(0, 7))} required maxLength={7} pattern="#[0-9A-Fa-f]{6}" placeholder="#12372A" className="field-control mt-0 font-mono uppercase" aria-label={`${label} HEX value`} /></span><span className="mt-2 block text-xs font-normal text-slate-500">Six-digit HEX, for example #F54492.</span></label>; }
function AssetUpload({ name, title, detail, currentUrl, currentLabel, square = false }: { name: string; title: string; detail: string; currentUrl?: string; currentLabel?: string; square?: boolean }) { const [preview, setPreview] = useState<string>(); useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]); const previewUrl = preview ?? currentUrl; return <label className="group rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5 transition hover:border-emerald-500 hover:bg-emerald-50/40"><span className="flex items-center gap-4">{previewUrl ? <Image unoptimized src={previewUrl} width={square ? 80 : 128} height={80} alt="Selected asset preview" className={`${square ? "size-20 rounded-2xl" : "h-20 w-32 rounded-xl"} bg-white object-contain p-2 shadow-sm`} /> : <span className={`${square ? "size-20 rounded-2xl" : "h-20 w-32 rounded-xl"} grid shrink-0 place-items-center bg-white text-sm font-black text-slate-400 shadow-sm`}>{square ? "LOGO" : "SIGN"}</span>}<span><span className="block font-black text-slate-900">{title}</span><span className="mt-1 block text-xs font-normal leading-5 text-slate-500">{detail}</span>{currentLabel && <span className="mt-2 block text-xs font-bold text-emerald-700">✓ {currentLabel}</span>}</span></span><input name={name} type="file" accept="image/png,image/jpeg" className="mt-4 block w-full text-sm text-slate-600 file:mr-4 file:cursor-pointer file:rounded-full file:border-0 file:bg-emerald-700 file:px-4 file:py-2 file:font-bold file:text-white" onChange={event => { const file = event.target.files?.[0]; if (preview) URL.revokeObjectURL(preview); setPreview(file ? URL.createObjectURL(file) : undefined); }} /></label>; }
function isHexColour(value?: string): value is string { return /^#[0-9A-Fa-f]{6}$/.test(value ?? ""); }
function announceBranding(profile: Pick<Profile, "primaryColor" | "secondaryColor" | "logoUrl">) { window.dispatchEvent(new CustomEvent("giddyedu:branding-preview", { detail: { primaryColor: profile.primaryColor, secondaryColor: profile.secondaryColor, logoUrl: profile.logoUrl } })); }
function CampusForm({ campuses, submit, disabled }: { campuses: Campus[]; submit: (event: FormEvent<HTMLFormElement>) => void; disabled: boolean }) {
  const [editing, setEditing] = useState<Campus | null>(null); const [deleting, setDeleting] = useState<Campus | null>(null); const [confirmation, setConfirmation] = useState(""); const [error, setError] = useState("");
  const [deletedCampusIds, setDeletedCampusIds] = useState<Set<string>>(() => new Set());
  const [workspaceAccess, setWorkspaceAccess] = useState<Access | null>(null);
  const visibleCampuses = campuses.filter(campus => !deletedCampusIds.has(campus.id));
  useEffect(() => { void fetch("/api/auth/session", { cache: "no-store" }).then(async response => { if (!response.ok) return; const body = await response.json() as { access: Access }; setWorkspaceAccess(body.access); }); }, []);
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const data = new FormData(event.currentTarget); const response = await fetch(`/api/backend/schools/campuses/${editing.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), isMainCampus: data.get("isMainCampus") === "yes" }) }); if (!response.ok) { setError(await apiError(response, "Campus could not be updated.")); return; } window.location.reload(); }
  async function remove() { if (!deleting || confirmation !== "DELETE") return; const deletedId = deleting.id; const response = await fetch(`/api/backend/schools/campuses/${deletedId}`, { method: "DELETE" }); if (!response.ok) { setError(await apiError(response, "Campus could not be deleted.")); return; } setDeletedCampusIds(current => new Set(current).add(deletedId)); setDeleting(null); setConfirmation(""); setError(""); }
  async function openWorkspace(campus: Campus) { if (!workspaceAccess) return; setError(""); const response = await fetch("/api/auth/switch-workspace", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tenantId: workspaceAccess.tenantId, campusId: campus.id }) }); if (!response.ok) { setError(await apiError(response, "Campus workspace could not be opened.")); return; } window.location.replace("/portal"); }
  return <section className="mt-8 grid gap-6 lg:grid-cols-[1.35fr_.65fr]">
    <div className="rounded-3xl bg-white p-6 shadow-sm">
      <h2 className="text-xl font-black">Campus workspaces</h2>
      <p className="mt-1 text-sm text-slate-500">Open a campus to make it the active workspace. Editing its record does not switch workspace.</p>
      {error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      <div className="mt-4 max-h-[30rem] space-y-3 overflow-y-auto pr-2">{visibleCampuses.map(campus => {
        const active = workspaceAccess?.campusId === campus.id;
        return <div key={campus.id} className={`flex flex-col gap-4 rounded-2xl border p-4 sm:flex-row sm:items-center sm:justify-between ${active ? "border-emerald-500 bg-emerald-50/60" : "border-slate-200"}`}>
          <div><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{campus.name}</p>{active && <span className="rounded-full bg-emerald-700 px-2 py-1 text-[10px] font-black uppercase tracking-wide text-white">Active workspace</span>}</div><p className="mt-1 text-sm text-slate-500">{campus.code} · {campus.isMainCampus ? "Main campus" : "Additional campus"}</p></div>
          <div className="flex flex-wrap gap-2"><button type="button" disabled={active || !workspaceAccess} onClick={() => void openWorkspace(campus)} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-bold text-white hover:bg-emerald-800 disabled:cursor-default disabled:bg-slate-200 disabled:text-slate-500">{active ? "Currently open" : "Open workspace"}</button><button type="button" disabled={disabled} onClick={() => { setEditing(campus); setError(""); }} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold hover:bg-slate-50">Edit</button><button type="button" disabled={disabled || visibleCampuses.length <= 1} onClick={() => { setDeleting(campus); setConfirmation(""); setError(""); }} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700 hover:bg-red-50 disabled:opacity-40">Delete</button></div>
        </div>;
      })}</div>
    </div>
    <form onSubmit={submit} className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Add campus</h2><p className="mt-1 text-sm text-slate-500">GiddyEdu generates and protects the campus code automatically.</p><div className="mt-4 space-y-4"><Input name="name" label="Campus name" required /><CampusMainSelect /><button disabled={disabled} className="w-full rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white disabled:opacity-50">Add campus</button></div></form>
    {editing && <Modal title="Edit campus" close={() => setEditing(null)}><form onSubmit={update} className="space-y-4"><Input name="name" label="Campus name" defaultValue={editing.name} required /><div className="rounded-xl bg-slate-100 px-4 py-3 text-sm"><span className="block text-xs font-bold text-slate-500">System campus code</span><span className="mt-1 block font-mono font-bold text-slate-800">{editing.code}</span></div><CampusMainSelect value={editing.isMainCampus ? "yes" : "no"} />{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={disabled} className="w-full rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">Update campus</button></form></Modal>}
    {deleting && <Modal title="Permanently delete campus" close={() => setDeleting(null)}><p className="text-sm leading-6 text-slate-600">This permanently deletes <strong>{deleting.name}</strong> and all data owned by its workspace. This cannot be recovered.</p><label className="mt-5 block text-sm font-bold">Type DELETE to confirm<input value={confirmation} onChange={event => setConfirmation(event.target.value)} autoComplete="off" className="field-control" /></label>{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}<button type="button" disabled={disabled || confirmation !== "DELETE"} onClick={() => void remove()} className="mt-5 w-full rounded-xl bg-red-700 px-5 py-3 font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">Delete campus permanently</button></Modal>}
  </section>;
}
function CampusMainSelect({ value = "no" }: { value?: string }) { return <label className="block text-sm font-semibold">Main campus?<select name="isMainCampus" required defaultValue={value} className="field-control"><option value="yes">Yes</option><option value="no">No</option></select></label>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div role="dialog" aria-modal="true" aria-label={title} className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4" onMouseDown={event => { if (event.target === event.currentTarget) close(); }}><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h3 className="text-xl font-black">{title}</h3><button type="button" onClick={close} aria-label="Close dialog" className="grid size-9 place-items-center rounded-full bg-slate-100 text-xl">×</button></div>{children}</div></div>; }
async function apiError(response: Response, fallback: string) { try { const body = await response.json() as { detail?: string; title?: string; message?: string }; return body.detail ?? body.message ?? body.title ?? fallback; } catch { return fallback; } }
function Input(props: React.InputHTMLAttributes<HTMLInputElement> & { label: string; helper?: string }) { const { label, helper, ...input } = props; return <label className="text-sm font-semibold">{label}<input {...input} className="field-control" />{helper && <span className="mt-2 block text-xs font-normal leading-5 text-slate-500">{helper}</span>}</label>; }
function Submit({ disabled, label }: { disabled: boolean; label: string }) { return <button disabled={disabled} className="rounded-xl bg-emerald-700 px-7 py-3 font-bold text-white shadow-sm transition hover:bg-emerald-800 disabled:opacity-50">{disabled ? "Unavailable" : label}</button>; }
function Panel({ children }: { children: React.ReactNode }) { return <div className="mx-auto max-w-3xl rounded-3xl bg-white p-8 text-slate-600">{children}</div>; }
