"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Profile = { displayName: string; legalName?: string; email?: string; phone?: string; websiteUrl?: string; address?: string; countryCode: string; timeZone: string; currencyCode: string; logoFileId?: string; primaryColor?: string; secondaryColor?: string };
type Campus = { id: string; name: string; code: string; isActive: boolean };
type Access = { tenantId: string; permissions: string[] };
const blankProfile: Profile = { displayName: "", countryCode: "NG", timeZone: "Africa/Lagos", currencyCode: "NGN", primaryColor: "#12372A", secondaryColor: "#10B981" };

export function SchoolOnboarding() {
  const router = useRouter();
  const [profile, setProfile] = useState<Profile>(blankProfile); const [campuses, setCampuses] = useState<Campus[]>([]); const [access, setAccess] = useState<Access | null>(null);
  const [step, setStep] = useState(0); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const canManage = access?.permissions.includes("Schools.Manage") === true;
  const completed = useMemo(() => [Boolean(profile.displayName && profile.email && profile.address), Boolean(profile.primaryColor && profile.secondaryColor), campuses.some(campus => campus.isActive)], [profile, campuses]);

  useEffect(() => { Promise.all([fetch("/api/auth/session", { cache: "no-store" }), fetch("/api/backend/schools/current", { cache: "no-store" }), fetch("/api/backend/schools/campuses", { cache: "no-store" })]).then(async ([sessionResponse, profileResponse, campusResponse]) => {
    if (sessionResponse.status === 401) { router.replace("/login"); return; }
    if (!sessionResponse.ok || !campusResponse.ok) throw new Error("School configuration could not be loaded.");
    const session = await sessionResponse.json() as { access?: Access }; setAccess(session.access ?? null);
    if (profileResponse.ok) setProfile({ ...blankProfile, ...(await profileResponse.json() as Profile) }); else if (profileResponse.status !== 404) throw new Error("School profile could not be loaded.");
    setCampuses(await campusResponse.json() as Campus[]);
  }).catch(error => setMessage(error instanceof Error ? error.message : "School configuration could not be loaded.")).finally(() => setLoading(false)); }, [router]);

  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await fetch("/api/backend/schools/current", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); if (!response.ok) throw new Error(response.status === 403 ? "You do not have permission to configure this school." : "Check the profile details and try again."); setMessage("School profile saved."); setStep(1); } catch (error) { setMessage(error instanceof Error ? error.message : "Profile could not be saved."); } finally { setBusy(false); } }
  async function saveBranding(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); try { const file = new FormData(event.currentTarget).get("logo"); let logoFileId = profile.logoFileId; if (file instanceof File && file.size > 0) logoFileId = await uploadLogo(file); const updated = { ...profile, logoFileId }; const response = await fetch("/api/backend/schools/current", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(updated) }); if (!response.ok) throw new Error(response.status === 403 ? "You do not have permission to update branding." : "Branding could not be saved."); setProfile(updated); setMessage("Branding saved."); setStep(2); } catch (error) { setMessage(error instanceof Error ? error.message : "Branding could not be saved."); } finally { setBusy(false); } }
  async function uploadLogo(file: File) { if (!access) throw new Error("Your tenant session is unavailable."); if (!["image/png", "image/jpeg"].includes(file.type) || file.size > 2 * 1024 * 1024) throw new Error("Choose a PNG or JPEG logo no larger than 2 MB."); const begin = await fetch("/api/backend/foundation/files", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fileName: file.name, contentType: file.type, sizeBytes: file.size, category: "branding-logo", entityType: "SchoolProfile", entityId: access.tenantId }) }); if (!begin.ok) throw new Error("Logo upload could not be started."); const upload = await begin.json() as { fileId: string; uploadUrl: string }; const stored = await fetch(upload.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!stored.ok) throw new Error("Logo could not be stored."); const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); const checksum = Array.from(new Uint8Array(digest), value => value.toString(16).padStart(2, "0")).join(""); const complete = await fetch(`/api/backend/foundation/files/${upload.fileId}/complete`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ checksum }) }); if (!complete.ok) throw new Error("Logo upload could not be verified."); return upload.fileId; }
  async function addCampus(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = event.currentTarget; const data = new FormData(form); try { const response = await fetch("/api/backend/schools/campuses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), code: data.get("code") }) }); if (!response.ok) throw new Error(response.status === 403 ? "You do not have permission to add campuses." : "Campus details could not be saved."); const refreshed = await fetch("/api/backend/schools/campuses", { cache: "no-store" }); setCampuses(await refreshed.json() as Campus[]); form.reset(); setMessage("Campus added."); } catch (error) { setMessage(error instanceof Error ? error.message : "Campus could not be saved."); } finally { setBusy(false); } }

  if (loading) return <Panel>Loading school setup…</Panel>;
  return <main className="min-h-screen bg-[#f6f4ee]"><header className="bg-[#12372a] text-white"><div className="mx-auto max-w-6xl px-6 py-5"><Link href="/portal" className="text-sm font-bold text-emerald-100">← Workspace</Link></div></header><div className="mx-auto max-w-6xl px-6 py-10"><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">School onboarding</p><h1 className="mt-2 text-4xl font-black">Configure your school</h1><p className="mt-2 text-slate-600">Complete the profile, branding and campus setup used throughout GiddyEdu.</p><ol className="mt-8 grid gap-3 sm:grid-cols-3">{["School profile", "Branding", "Campuses"].map((label, index) => <li key={label}><button type="button" onClick={() => setStep(index)} className={`w-full rounded-2xl border p-4 text-left font-bold ${step === index ? "border-emerald-700 bg-emerald-50" : "border-slate-200 bg-white"}`}><span className="mr-2">{completed[index] ? "✓" : index + 1}</span>{label}</button></li>)}</ol>{!canManage && <p role="alert" className="mt-6 rounded-2xl bg-amber-50 p-4 text-amber-900">You can view this setup, but Schools.Manage permission is required to change it.</p>}{step === 0 && <ProfileForm profile={profile} setProfile={setProfile} submit={saveProfile} disabled={!canManage || busy} />}{step === 1 && <BrandingForm profile={profile} setProfile={setProfile} submit={saveBranding} disabled={!canManage || busy} />}{step === 2 && <CampusForm campuses={campuses} submit={addCampus} disabled={!canManage || busy} />}{message && <p role="status" className="mt-5 rounded-2xl bg-white p-4 text-sm text-slate-700">{message}</p>}</div></main>;
}

function ProfileForm({ profile, setProfile, submit, disabled }: { profile: Profile; setProfile: (value: Profile) => void; submit: (event: FormEvent<HTMLFormElement>) => void; disabled: boolean }) { const field = (key: keyof Profile) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setProfile({ ...profile, [key]: event.target.value }); return <form onSubmit={submit} className="mt-8 grid gap-4 rounded-3xl bg-white p-6 shadow-sm sm:grid-cols-2"><Input label="Display name" value={profile.displayName} onChange={field("displayName")} required /><Input label="Legal name" value={profile.legalName ?? ""} onChange={field("legalName")} /><Input label="School email" type="email" value={profile.email ?? ""} onChange={field("email")} required /><Input label="Phone" value={profile.phone ?? ""} onChange={field("phone")} /><Input label="Website" type="url" value={profile.websiteUrl ?? ""} onChange={field("websiteUrl")} /><Input label="Country code" value={profile.countryCode} onChange={field("countryCode")} required maxLength={2} /><Input label="Timezone" value={profile.timeZone} onChange={field("timeZone")} required /><Input label="Currency" value={profile.currencyCode} onChange={field("currencyCode")} required maxLength={3} /><label className="sm:col-span-2 text-sm font-semibold">Address<textarea value={profile.address ?? ""} onChange={field("address")} required className="mt-1 min-h-28 w-full rounded-xl border border-slate-300 px-4 py-3" /></label><Submit disabled={disabled} label="Save profile and continue" /></form>; }
function BrandingForm({ profile, setProfile, submit, disabled }: { profile: Profile; setProfile: (value: Profile) => void; submit: (event: FormEvent<HTMLFormElement>) => void; disabled: boolean }) { return <form onSubmit={submit} className="mt-8 grid gap-5 rounded-3xl bg-white p-6 shadow-sm sm:grid-cols-2"><label className="text-sm font-semibold">Primary colour<input type="color" value={profile.primaryColor ?? "#12372A"} onChange={event => setProfile({ ...profile, primaryColor: event.target.value.toUpperCase() })} className="mt-1 h-14 w-full rounded-xl border border-slate-300 p-2" /></label><label className="text-sm font-semibold">Secondary colour<input type="color" value={profile.secondaryColor ?? "#10B981"} onChange={event => setProfile({ ...profile, secondaryColor: event.target.value.toUpperCase() })} className="mt-1 h-14 w-full rounded-xl border border-slate-300 p-2" /></label><label className="sm:col-span-2 text-sm font-semibold">School logo (PNG or JPEG, maximum 2 MB)<input name="logo" type="file" accept="image/png,image/jpeg" className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3" /></label><div className="sm:col-span-2 rounded-2xl p-6 text-white" style={{ background: `linear-gradient(135deg, ${profile.primaryColor}, ${profile.secondaryColor})` }}><p className="text-xs uppercase tracking-widest">Brand preview</p><p className="mt-2 text-2xl font-black">{profile.displayName || "Your school"}</p></div><Submit disabled={disabled} label="Save branding and continue" /></form>; }
function CampusForm({ campuses, submit, disabled }: { campuses: Campus[]; submit: (event: FormEvent<HTMLFormElement>) => void; disabled: boolean }) { return <section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Current campuses</h2><div className="mt-4 space-y-3">{campuses.map(campus => <div key={campus.id} className="rounded-2xl border border-slate-200 p-4"><p className="font-bold">{campus.name}</p><p className="text-sm text-slate-500">{campus.code} · {campus.isActive ? "Active" : "Inactive"}</p></div>)}</div></div><form onSubmit={submit} className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Add another campus</h2><div className="mt-4 space-y-4"><Input name="name" label="Campus name" required /><Input name="code" label="Campus code" required /><button disabled={disabled} className="w-full rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white disabled:opacity-50">Add campus</button></div></form></section>; }
function Input(props: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { const { label, ...input } = props; return <label className="text-sm font-semibold">{label}<input {...input} className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3" /></label>; }
function Submit({ disabled, label }: { disabled: boolean; label: string }) { return <button disabled={disabled} className="sm:col-span-2 rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white disabled:opacity-50">{disabled ? "Unavailable" : label}</button>; }
function Panel({ children }: { children: React.ReactNode }) { return <main className="min-h-screen bg-[#f6f4ee] p-10"><div className="mx-auto max-w-3xl rounded-3xl bg-white p-8 text-slate-600">{children}</div></main>; }
