"use client";

import { FormEvent, useEffect, useId, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { nigeriaLocations, nigeriaStates } from "@/lib/nigeria-locations";

type Profile = { displayName: string; schoolSlug: string; schoolType: string; legalName?: string; tagline?: string; email?: string; phone?: string; websiteUrl?: string; address?: string; state?: string; localGovernment?: string; countryCode: string; timeZone: string; currencyCode: string; dateFormat: string; timeFormat: string; customDomain?: string; logoFileId?: string; primaryColor?: string; secondaryColor?: string };
type Campus = { id: string; name: string; code: string; isMainCampus: boolean; isActive: boolean };
type Access = { tenantId: string; permissions: string[] };
const blankProfile: Profile = { displayName: "", schoolSlug: "", schoolType: "Not specified", countryCode: "NG", timeZone: "Africa/Lagos", currencyCode: "NGN", dateFormat: "dd/MM/yyyy", timeFormat: "HH:mm", primaryColor: "#12372A", secondaryColor: "#10B981" };

export function SchoolOnboarding() {
  const router = useRouter();
  const [profile, setProfile] = useState<Profile>(blankProfile); const [campuses, setCampuses] = useState<Campus[]>([]); const [access, setAccess] = useState<Access | null>(null);
  const [step, setStep] = useState(0); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const canManage = access?.permissions.includes("Schools.Manage") === true;
  const completed = useMemo(() => [Boolean(profile.displayName && profile.legalName && profile.email && profile.address && profile.state && profile.localGovernment), Boolean(profile.primaryColor && profile.secondaryColor), campuses.some(campus => campus.isActive)], [profile, campuses]);

  useEffect(() => { Promise.all([fetch("/api/auth/session", { cache: "no-store" }), fetch("/api/backend/schools/current", { cache: "no-store" }), fetch("/api/backend/schools/campuses", { cache: "no-store" })]).then(async ([sessionResponse, profileResponse, campusResponse]) => {
    if (sessionResponse.status === 401) { router.replace("/login"); return; }
    if (!sessionResponse.ok || !campusResponse.ok) throw new Error("School configuration could not be loaded.");
    const session = await sessionResponse.json() as { access?: Access }; setAccess(session.access ?? null);
    if (profileResponse.ok) { const loaded = await profileResponse.json() as Profile; setProfile({ ...blankProfile, ...loaded, legalName: loaded.legalName || loaded.displayName, dateFormat: loaded.dateFormat || blankProfile.dateFormat, timeFormat: loaded.timeFormat || blankProfile.timeFormat }); } else if (profileResponse.status !== 404) throw new Error("School profile could not be loaded.");
    setCampuses(await campusResponse.json() as Campus[]);
  }).catch(error => setMessage(error instanceof Error ? error.message : "School configuration could not be loaded.")).finally(() => setLoading(false)); }, [router]);

  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await fetch("/api/backend/schools/current", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); if (!response.ok) throw new Error(response.status === 403 ? "You do not have permission to configure this school." : "Check the profile details and try again."); setMessage("School profile saved."); setStep(1); } catch (error) { setMessage(error instanceof Error ? error.message : "Profile could not be saved."); } finally { setBusy(false); } }
  async function saveBranding(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); try { const file = new FormData(event.currentTarget).get("logo"); let logoFileId = profile.logoFileId; if (file instanceof File && file.size > 0) logoFileId = await uploadLogo(file); const updated = { ...profile, logoFileId }; const response = await fetch("/api/backend/schools/current", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(updated) }); if (!response.ok) throw new Error(response.status === 403 ? "You do not have permission to update branding." : "Branding could not be saved."); setProfile(updated); setMessage("Branding saved."); setStep(2); } catch (error) { setMessage(error instanceof Error ? error.message : "Branding could not be saved."); } finally { setBusy(false); } }
  async function uploadLogo(file: File) { if (!access) throw new Error("Your tenant session is unavailable."); if (!["image/png", "image/jpeg"].includes(file.type) || file.size > 2 * 1024 * 1024) throw new Error("Choose a PNG or JPEG logo no larger than 2 MB."); const begin = await fetch("/api/backend/foundation/files", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fileName: file.name, contentType: file.type, sizeBytes: file.size, category: "branding-logo", entityType: "SchoolProfile", entityId: access.tenantId }) }); if (!begin.ok) throw new Error("Logo upload could not be started."); const upload = await begin.json() as { fileId: string; uploadUrl: string }; const stored = await fetch(upload.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!stored.ok) throw new Error("Logo could not be stored."); const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); const checksum = Array.from(new Uint8Array(digest), value => value.toString(16).padStart(2, "0")).join(""); const complete = await fetch(`/api/backend/foundation/files/${upload.fileId}/complete`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ checksum }) }); if (!complete.ok) throw new Error("Logo upload could not be verified."); return upload.fileId; }
  async function addCampus(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = event.currentTarget; const data = new FormData(form); try { const response = await fetch("/api/backend/schools/campuses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), code: data.get("code"), isMainCampus: data.get("isMainCampus") === "yes" }) }); if (!response.ok) throw new Error(response.status === 403 ? "You do not have permission to add campuses." : "Campus details could not be saved."); const refreshed = await fetch("/api/backend/schools/campuses", { cache: "no-store" }); setCampuses(await refreshed.json() as Campus[]); form.reset(); setMessage("Campus added."); } catch (error) { setMessage(error instanceof Error ? error.message : "Campus could not be saved."); } finally { setBusy(false); } }

  if (loading) return <Panel>Loading school setup…</Panel>;
  return <section className="w-full"><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">School onboarding</p><h1 className="mt-2 text-3xl font-black text-slate-950 sm:text-4xl">Configure your school</h1><p className="mt-2 text-slate-600">Complete the profile, branding and campus setup used throughout GiddyEdu.</p><ol className="mt-8 grid gap-3 sm:grid-cols-3">{["School profile", "Branding", "Campuses"].map((label, index) => <li key={label}><button type="button" onClick={() => setStep(index)} className={`w-full rounded-2xl border p-4 text-left font-bold transition ${step === index ? "border-emerald-700 bg-emerald-50 text-emerald-950" : "border-slate-200 bg-white hover:border-emerald-300"}`}><span className="mr-2">{completed[index] ? "✓" : index + 1}</span>{label}</button></li>)}</ol>{!canManage && <p role="alert" className="mt-6 rounded-2xl bg-amber-50 p-4 text-amber-900">You can view this setup, but Schools.Manage permission is required to change it.</p>}{step === 0 && <ProfileForm profile={profile} setProfile={setProfile} submit={saveProfile} disabled={!canManage || busy} />}{step === 1 && <BrandingForm profile={profile} setProfile={setProfile} submit={saveBranding} disabled={!canManage || busy} />}{step === 2 && <CampusForm campuses={campuses} submit={addCampus} disabled={!canManage || busy} />}{message && <p role="status" className="mt-5 rounded-2xl bg-white p-4 text-sm text-slate-700">{message}</p>}</section>;
}

function ProfileForm({ profile, setProfile, submit, disabled }: { profile: Profile; setProfile: (value: Profile) => void; submit: (event: FormEvent<HTMLFormElement>) => void; disabled: boolean }) {
  const field = (key: keyof Profile) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setProfile({ ...profile, [key]: event.target.value });
  const localGovernments = profile.state && profile.state in nigeriaLocations ? [...nigeriaLocations[profile.state as keyof typeof nigeriaLocations]] : [];
  const sectionClass = "rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7";
  return <form onSubmit={submit} className="mt-8 space-y-5">
    <section className={sectionClass}>
      <SectionHeading eyebrow="School identity" title="Basic details" description="The official details used across records, communications and reports." />
      <div className="mt-6 grid gap-5 sm:grid-cols-2">
        <Input label="School name" value={profile.displayName} onChange={field("displayName")} required />
        <Input label="Legal name" value={profile.legalName ?? profile.displayName} onChange={field("legalName")} required helper="Pre-filled from registration and editable when the registered legal name differs." />
        <label className="text-sm font-semibold">School type<select value={profile.schoolType} onChange={field("schoolType")} required className="field-control"><option value="Not specified" disabled>Select school type</option>{["Nursery", "Primary", "Secondary", "Primary and Secondary", "Nursery, Primary and Secondary"].map(value => <option key={value}>{value}</option>)}</select></label>
        <Input label="School tagline" value={profile.tagline ?? ""} onChange={field("tagline")} maxLength={160} placeholder="Inspiring every learner to thrive" />
      </div>
    </section>
    <section className={sectionClass}>
      <SectionHeading eyebrow="How families reach you" title="Contact and location" description="Keep these details accurate for school correspondence and location-aware services." />
      <div className="mt-6 grid gap-5 sm:grid-cols-2">
        <Input label="School email" type="email" value={profile.email ?? ""} onChange={field("email")} required />
        <Input label="School phone" type="tel" inputMode="numeric" autoComplete="tel" value={profile.phone ?? ""} onChange={event => setProfile({ ...profile, phone: event.target.value.replace(/\D/g, "").slice(0, 11) })} placeholder="09096735531" minLength={11} maxLength={11} pattern="[0-9]{11}" helper="Enter exactly 11 digits without spaces or symbols." />
        <Input label="School website" type="url" value={profile.websiteUrl ?? ""} onChange={field("websiteUrl")} placeholder="https://www.yourschool.edu.ng" />
        <div className="hidden sm:block" />
        <SearchableSelect label="State" value={profile.state ?? ""} options={nigeriaStates} placeholder="Search Nigerian states" required onChange={state => setProfile({ ...profile, state, localGovernment: nigeriaLocations[state as keyof typeof nigeriaLocations]?.includes(profile.localGovernment as never) ? profile.localGovernment : "" })} />
        <SearchableSelect label="Local government area" value={profile.localGovernment ?? ""} options={localGovernments} placeholder={profile.state ? "Search local government areas" : "Select a state first"} required disabled={!profile.state} onChange={localGovernment => setProfile({ ...profile, localGovernment })} />
        <label className="text-sm font-semibold sm:col-span-2">Full school address<textarea value={profile.address ?? ""} onChange={field("address")} required placeholder="Street, town or district, and nearest landmark" className="field-control min-h-28 resize-y" /></label>
      </div>
    </section>
    <section className={sectionClass}>
      <SectionHeading eyebrow="Local preferences" title="Regional settings" description="These defaults control how dates, times and amounts appear across your workspace." />
      <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <ReadOnlyField label="Country" value="Nigeria" />
        <label className="text-sm font-semibold">Time zone<select value={profile.timeZone} onChange={field("timeZone")} required className="field-control"><option value="Africa/Lagos">West Africa Time (Lagos)</option></select></label>
        <label className="text-sm font-semibold">Currency<select value={profile.currencyCode} onChange={field("currencyCode")} required className="field-control"><option value="NGN">Nigerian Naira (NGN)</option></select></label>
        <label className="text-sm font-semibold">Country code<select value={profile.countryCode} onChange={field("countryCode")} required className="field-control"><option value="NG">NG · Nigeria</option></select></label>
        <label className="text-sm font-semibold">Date format<select value={profile.dateFormat} onChange={field("dateFormat")} required className="field-control"><option value="dd/MM/yyyy">DD/MM/YYYY</option><option value="MM/dd/yyyy">MM/DD/YYYY</option><option value="yyyy-MM-dd">YYYY-MM-DD</option></select></label>
        <label className="text-sm font-semibold">Time format<select value={profile.timeFormat} onChange={field("timeFormat")} required className="field-control"><option value="HH:mm">24-hour (14:30)</option><option value="hh:mm tt">12-hour (02:30 PM)</option></select></label>
      </div>
    </section>
    <section className={sectionClass}>
      <SectionHeading eyebrow="Your web address" title="Domain settings" description="Use the included GiddyEdu address now, and connect a branded domain when you are ready." />
      <div className="mt-6 grid gap-5 lg:grid-cols-2">
        <label className="text-sm font-semibold">Default GiddyEdu domain<div className="mt-1 flex overflow-hidden rounded-xl border border-slate-300 bg-white focus-within:border-emerald-600 focus-within:ring-2 focus-within:ring-emerald-100"><input value={profile.schoolSlug} onChange={event => setProfile({ ...profile, schoolSlug: slugify(event.target.value) })} required minLength={3} maxLength={100} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" className="min-w-0 flex-1 px-4 py-3 outline-none" /><span className="flex items-center border-l border-slate-200 bg-slate-50 px-3 text-sm text-slate-500">.giddyedu.com</span></div><span className="mt-2 block text-xs text-slate-500">Included with your workspace. Changes must remain unique.</span></label>
        <Input label="Custom domain (optional)" value={profile.customDomain ?? ""} onChange={field("customDomain")} placeholder="portal.yourschool.edu.ng" helper="Enter only the domain name. DNS verification will be completed before it becomes active." />
      </div>
    </section>
    <div className="flex justify-end"><Submit disabled={disabled} label="Save profile and continue" /></div>
  </form>;
}

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">{eyebrow}</p><h2 className="mt-1 text-xl font-black text-slate-950">{title}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">{description}</p></div>; }
function ReadOnlyField({ label, value }: { label: string; value: string }) { return <label className="text-sm font-semibold">{label}<span className="field-control block bg-slate-50 text-slate-600">{value}</span></label>; }
function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/-+/g, "-").replace(/^-/, ""); }

function SearchableSelect({ label, value, options, placeholder, required, disabled, onChange }: { label: string; value: string; options: readonly string[]; placeholder: string; required?: boolean; disabled?: boolean; onChange: (value: string) => void }) {
  const id = useId(); const [open, setOpen] = useState(false); const [query, setQuery] = useState("");
  const visibleValue = open ? query : value;
  const filtered = options.filter(option => option.toLowerCase().includes(visibleValue.toLowerCase())).slice(0, 50);
  return <label htmlFor={id} className="relative text-sm font-semibold">{label}
    <input id={id} role="combobox" aria-expanded={open} aria-controls={`${id}-options`} autoComplete="off" value={visibleValue} placeholder={placeholder} disabled={disabled} required={required} onFocus={() => { setQuery(value); setOpen(true); }} onBlur={() => window.setTimeout(() => setOpen(false), 120)} onChange={event => { setQuery(event.target.value); onChange(""); setOpen(true); }} className="field-control" />
    {open && !disabled && <ul id={`${id}-options`} role="listbox" className="absolute z-20 mt-1 max-h-60 w-full overflow-auto rounded-xl border border-slate-200 bg-white p-1 shadow-xl">{filtered.length ? filtered.map(option => <li key={option}><button type="button" role="option" aria-selected={value === option} onMouseDown={event => event.preventDefault()} onClick={() => { onChange(option); setQuery(option); setOpen(false); }} className="w-full rounded-lg px-3 py-2 text-left text-sm font-medium hover:bg-emerald-50 hover:text-emerald-900">{option}</button></li>) : <li className="px-3 py-3 text-sm font-normal text-slate-500">No matching option</li>}</ul>}
  </label>;
}
function BrandingForm({ profile, setProfile, submit, disabled }: { profile: Profile; setProfile: (value: Profile) => void; submit: (event: FormEvent<HTMLFormElement>) => void; disabled: boolean }) { return <form onSubmit={submit} className="mt-8 grid gap-5 rounded-3xl bg-white p-6 shadow-sm sm:grid-cols-2"><label className="text-sm font-semibold">Primary colour<input type="color" value={profile.primaryColor ?? "#12372A"} onChange={event => setProfile({ ...profile, primaryColor: event.target.value.toUpperCase() })} className="mt-1 h-14 w-full rounded-xl border border-slate-300 p-2" /></label><label className="text-sm font-semibold">Secondary colour<input type="color" value={profile.secondaryColor ?? "#10B981"} onChange={event => setProfile({ ...profile, secondaryColor: event.target.value.toUpperCase() })} className="mt-1 h-14 w-full rounded-xl border border-slate-300 p-2" /></label><label className="sm:col-span-2 text-sm font-semibold">School logo (PNG or JPEG, maximum 2 MB)<input name="logo" type="file" accept="image/png,image/jpeg" className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3" /></label><div className="sm:col-span-2 rounded-2xl p-6 text-white" style={{ background: `linear-gradient(135deg, ${profile.primaryColor}, ${profile.secondaryColor})` }}><p className="text-xs uppercase tracking-widest">Brand preview</p><p className="mt-2 text-2xl font-black">{profile.displayName || "Your school"}</p></div><Submit disabled={disabled} label="Save branding and continue" /></form>; }
function CampusForm({ campuses, submit, disabled }: { campuses: Campus[]; submit: (event: FormEvent<HTMLFormElement>) => void; disabled: boolean }) { return <section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Current campuses</h2><div className="mt-4 space-y-3">{campuses.map(campus => <div key={campus.id} className="rounded-2xl border border-slate-200 p-4"><p className="font-bold">{campus.name}</p><p className="text-sm text-slate-500">{campus.code} · Main campus: {campus.isMainCampus ? "Yes" : "No"} · {campus.isActive ? "Active" : "Inactive"}</p></div>)}</div></div><form onSubmit={submit} className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Add another campus</h2><div className="mt-4 space-y-4"><Input name="name" label="Campus name" required /><Input name="code" label="Campus code" required /><label className="block text-sm font-semibold">Main campus?<select name="isMainCampus" required defaultValue="no" className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3"><option value="yes">Yes</option><option value="no">No</option></select></label><button disabled={disabled} className="w-full rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white disabled:opacity-50">Add campus</button></div></form></section>; }
function Input(props: React.InputHTMLAttributes<HTMLInputElement> & { label: string; helper?: string }) { const { label, helper, ...input } = props; return <label className="text-sm font-semibold">{label}<input {...input} className="field-control" />{helper && <span className="mt-2 block text-xs font-normal leading-5 text-slate-500">{helper}</span>}</label>; }
function Submit({ disabled, label }: { disabled: boolean; label: string }) { return <button disabled={disabled} className="rounded-xl bg-emerald-700 px-7 py-3 font-bold text-white shadow-sm transition hover:bg-emerald-800 disabled:opacity-50">{disabled ? "Unavailable" : label}</button>; }
function Panel({ children }: { children: React.ReactNode }) { return <div className="mx-auto max-w-3xl rounded-3xl bg-white p-8 text-slate-600">{children}</div>; }
