"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { notify } from "@/components/app-toast";
import { nigeriaLocations } from "@/lib/nigeria-locations";
import { SearchableCombobox } from "@/components/resource-page";

type Option = { id: string; name: string };
type Structure = { departments?: Option[] };
const steps = ["Employment", "Personal", "Medical", "Qualifications", "Contact", "Documents"] as const;
const input = "mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-2.5 text-sm outline-none transition focus:border-[var(--tenant-primary,#28654a)] focus:ring-4 focus:ring-emerald-950/5";
const label = "block text-xs font-bold text-slate-700";

export function StaffRegistrationWizard({ onCreated }: { onCreated?: () => void }) {
  const [open, setOpen] = useState(false); const [step, setStep] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [showDocumentNotice, setShowDocumentNotice] = useState(true);
  useEffect(() => { if (!error) return; const timeout = window.setTimeout(() => setError(""), 5000); return () => window.clearTimeout(timeout); }, [error]);
  useEffect(() => { if (!open || step !== 5 || !showDocumentNotice) return; const timeout = window.setTimeout(() => setShowDocumentNotice(false), 7000); return () => window.clearTimeout(timeout); }, [open, step, showDocumentNotice]);
  const [draft, setDraft] = useState<Record<string, FormDataEntryValue>>({});
  const [departments, setDepartments] = useState<Option[]>([]);
  const [category, setCategory] = useState(""); const [state, setState] = useState(""); const [qualification, setQualification] = useState(false); const [qualificationName, setQualificationName] = useState("");
  const lgas = useMemo(() => state ? nigeriaLocations[state as keyof typeof nigeriaLocations] ?? [] : [], [state]);
  const rememberPosition = useCallback((value: string) => setDraft(current => ({...current, positionId:value})), []);

  useEffect(() => { if (!open) return; void fetch("/api/backend/academics/structure").then(r => r.ok ? r.json() : {}).then(structure => setDepartments((structure as Structure).departments ?? [])); }, [open]);

  async function upload(staffId: string, file: File, categoryName: string) {
    const begin = await fetch(`/api/backend/documents/StaffProfile/${staffId}/uploads`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({fileName:file.name, contentType:file.type, sizeBytes:file.size, category:categoryName}) });
    if (!begin.ok) throw new Error(`${categoryName === "photo" ? "Photograph" : "Signature"} upload could not be started.`);
    const details = await begin.json() as { fileId:string; uploadUrl:string }; const stored = await fetch(details.uploadUrl, {method:"PUT",headers:{"Content-Type":file.type},body:file});
    if (!stored.ok) throw new Error("A document could not be stored.");
    const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); const checksum = Array.from(new Uint8Array(digest), value => value.toString(16).padStart(2,"0")).join("");
    const complete = await fetch(`/api/backend/documents/${details.fileId}/complete`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({checksum})});
    if (!complete.ok) throw new Error("A document upload could not be verified.");
  }

  function continueRegistration(form: HTMLFormElement | null) {
    if (!form?.reportValidity()) return;
    if (step === 4) {
      const contact = new FormData(form);
      if (!/^\d{11}$/.test(String(contact.get("phone") ?? ""))) { setError("Phone number must contain exactly 11 digits."); return; }
    }
    setError("");
    setStep(current => current + 1);
  }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget);
    let createdStaffId: string | null = null;
    try {
      for (const [name, value] of Object.entries(draft)) if (!data.has(name)) data.set(name, value);
      const phone = String(data.get("phone") ?? ""); if (!/^\d{11}$/.test(phone)) { setStep(4); throw new Error("Phone number must contain exactly 11 digits."); }
      const email = String(data.get("email") ?? "").trim(); if (!email) { setStep(4); throw new Error("Email address is required."); }
      const staffResponse = await fetch("/api/backend/hr/staff", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({firstName:data.get("firstName"),lastName:data.get("lastName"),category:Number(data.get("category")),campusId:"00000000-0000-0000-0000-000000000000",departmentId:data.get("departmentId")||null,positionId:data.get("positionId")||null,email,phone,hireDate:data.get("hireDate"),status:Number(data.get("status"))})});
      if (!staffResponse.ok) throw new Error(await problem(staffResponse, "The staff profile could not be created."));
      const created = await staffResponse.json() as { id?:string }; const staffId = created.id ?? String(created); if (!staffId) throw new Error("The created staff record could not be identified."); createdStaffId = staffId;
      const social = [{platform:data.get("socialPlatform"),id:data.get("socialId")}].filter(x => x.platform && x.id);
      const sensitive = await fetch(`/api/backend/hr/staff/${staffId}/sensitive`, {method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({address:data.get("address")||null,notes:data.get("notes")||null,title:data.get("title")||null,middleName:data.get("middleName")||null,gender:data.get("gender")||null,dateOfBirth:data.get("dateOfBirth")||null,maritalStatus:data.get("maritalStatus")||null,religion:data.get("religion")||null,country:"Nigeria",state:data.get("state")||null,localGovernment:data.get("localGovernment")||null,city:data.get("city")||null,genotype:data.get("genotype")||null,bloodGroup:data.get("bloodGroup")||null,weightKg:numberOrNull(data.get("weightKg")),heightCm:numberOrNull(data.get("heightCm")),disability:data.get("disability")||null,skills:data.get("skills")||null,achievements:data.get("achievements")||null,website:data.get("website")||null,officeAddress:data.get("officeAddress")||null,socialProfilesJson:social.length?JSON.stringify(social):null})});
      if (!sensitive.ok) throw new Error(await problem(sensitive, "The private staff details could not be saved."));
      if (data.get("qualificationName")) { const selected=String(data.get("qualificationName")); const resolvedName=selected==="Other"?String(data.get("otherQualification")??"").trim():selected; if(!resolvedName) throw new Error("Enter the qualification details for Other."); const response = await fetch(`/api/backend/hr/staff/${staffId}/qualifications`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({institution:data.get("institution"),name:resolvedName,fieldOfStudy:data.get("fieldOfStudy")||null,awardedOn:data.get("awardedOn"),grade:data.get("grade")||null})}); if(!response.ok) throw new Error(await problem(response,"The qualification could not be saved.")); }
      for (const [fieldName, categoryName] of [["photo","photo"],["signature","signature"],["qualificationDocument","qualification"]] as const) { const file=data.get(fieldName); if(file instanceof File && file.size) await upload(staffId,file,categoryName); }
      const invitation = await fetch("/api/backend/account-invitations", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({targetType:0,targetId:staffId})});
      if (!invitation.ok) throw new Error(await problem(invitation, "The staff invitation could not be queued."));
      notify({title:"Staff created and invited",message:`A welcome email with a secure password-setup link has been queued for ${email}.`}); setOpen(false); setStep(0); setDraft({}); setCategory(""); setState(""); setQualification(false); setQualificationName(""); setShowDocumentNotice(true); event.currentTarget.reset(); onCreated?.();
    } catch (reason) { const message=reason instanceof Error?reason.message:"The staff record could not be created."; if (createdStaffId) { notify({tone:"error",title:"Staff record saved; setup incomplete",message:`${message} Open the staff record to finish setup or resend its invitation.`}); setOpen(false); onCreated?.(); } else setError(message); }
    finally { setBusy(false); }
  }

  return <div>
    <button type="button" onClick={() => setOpen(true)} className="tenant-primary-bg rounded-xl px-4 py-2.5 text-sm font-black text-white shadow-sm transition hover:-translate-y-0.5">Add staff member</button>
    {open && <div className="fixed inset-0 z-[120] bg-slate-950/45 p-3 backdrop-blur-sm sm:p-6" role="dialog" aria-modal="true" aria-label="Register staff member"><div className="mx-auto flex h-full max-w-6xl flex-col overflow-hidden rounded-[1.75rem] bg-white shadow-2xl">
      <header className="flex items-start justify-between border-b border-slate-200 px-5 py-4 sm:px-7"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-700">Staff registration</p><h2 className="mt-1 text-xl font-black text-slate-950 sm:text-2xl">Create a complete staff record</h2><p className="mt-1 text-xs text-slate-500">The staff number is generated securely after submission.</p></div><button type="button" onClick={() => setOpen(false)} className="grid size-10 place-items-center rounded-full bg-slate-100 text-xl hover:bg-red-50 hover:text-red-700" aria-label="Close">×</button></header>
      <nav className="flex gap-1 overflow-x-auto border-b border-slate-200 px-4 py-3 sm:px-7">{steps.map((name,index)=><button type="button" key={name} onClick={()=>setStep(index)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-black ${step===index?"tenant-primary-bg text-white":"text-slate-500 hover:bg-slate-100 hover:text-slate-900"}`}>{name}</button>)}</nav>
      <form onSubmit={submit} onChange={event=>{const target=event.target as unknown as HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement;if(!target.name)return;const value=target instanceof HTMLInputElement&&target.type==="file"?target.files?.[0]:target.value;if(value!==undefined)setDraft(current=>({...current,[target.name]:value}));}} className="flex min-h-0 flex-1 flex-col"><div className="flex-1 overflow-y-auto p-5 sm:p-7">
        {step===0&&<Panel title="Employment details" note="The staff member is assigned automatically to your active campus workspace."><Grid><Field name="firstName" title="First name" required/><Field name="middleName" title="Middle name"/><Field name="lastName" title="Last name" required/><Select name="category" title="Category" value={category} onChange={setCategory} options={[["0","Teaching"],["1","Administrative"],["2","Non-teaching"]]}/><label className={label}>Position<SearchableCombobox field={{name:"positionId",label:"Position",type:"combobox",required:false,optionsEndpoint:"hr/positions",optionLabelKey:"name",optionContextKey:"categoryName",manageEndpoint:"hr/positions"}} onValueChange={rememberPosition}/></label><Select name="departmentId" title="Department" optional options={departments.map(x=>[x.id,x.name])}/><Field name="hireDate" title="Hire date" type="date" required/><Select name="status" title="Initial account status" options={[["0","Active"],["3","Away"],["4","Not cleared"],["5","Inactive"],["6","On leave"],["7","Retired"],["8","Resigned"],["9","Sacked"],["10","Left"],["11","Deceased"]]} note="Only staff-relevant statuses are available; student statuses are intentionally excluded."/></Grid></Panel>}
        {step===1&&<Panel title="Personal details" note="Identity and residential details are restricted to authorised staff managers."><Grid><Select name="title" title="Title" optional options={[["Mr","Mr"],["Mrs","Mrs"],["Miss","Miss"],["Dr","Dr"],["Prof","Prof"]]}/><Select name="gender" title="Gender" optional options={[["Male","Male"],["Female","Female"],["Other","Other"],["Prefer not to say","Prefer not to say"]]}/><Field name="dateOfBirth" title="Date of birth" type="date"/><Select name="maritalStatus" title="Marital status" optional options={[["Single","Single"],["Married","Married"],["Divorced","Divorced"],["Widowed","Widowed"]]}/><Field name="religion" title="Religion"/><Field name="country" title="Country" value="Nigeria" readOnly/><Select name="state" title="State" optional value={state} onChange={setState} options={Object.keys(nigeriaLocations).map(x=>[x,x])}/><Select name="localGovernment" title="Local government" optional disabled={!state} options={lgas.map(x=>[x,x])}/><Field name="city" title="City / town"/><Area name="address" title="Residential address" wide/></Grid></Panel>}
        {step===2&&<Panel title="Medical information" note="Medical information is sensitive and is available only through the protected staff-sensitive permission."><Grid><Select name="genotype" title="Genotype" optional options={["AA","AS","AC","SS","SC","CC"].map(x=>[x,x])}/><Select name="bloodGroup" title="Blood group" optional options={["A+","A-","B+","B-","AB+","AB-","O+","O-"].map(x=>[x,x])}/><Field name="weightKg" title="Weight (kg)" type="number"/><Field name="heightCm" title="Height (cm)" type="number"/><Area name="disability" title="Disability or accessibility needs" wide/></Grid></Panel>}
        {step===3&&<Panel title="Qualifications and capabilities" note="Add the highest or most relevant qualification now. More qualifications can be added from the staff profile."><label className="mb-5 flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={qualification} onChange={e=>setQualification(e.target.checked)} className="size-4"/> Add a formal qualification</label>{qualification&&<Grid><Field name="institution" title="Institution" required/><Select name="qualificationName" title="Qualification" value={qualificationName} onChange={setQualificationName} options={["SSCE / WAEC","SSCE / NECO","NABTEB","NCE","OND","HND","Certificate","Diploma","Bachelor's degree","PGDE","Postgraduate diploma","Master's degree","MPhil","Professional qualification","PhD / Doctorate","Other"].map(x=>[x,x])}/>{qualificationName==="Other"&&<Field name="otherQualification" title="Other qualification details" required/>}<Field name="fieldOfStudy" title="Field of study"/><Field name="awardedOn" title="Date awarded" type="date" required/><Field name="grade" title="Grade / class"/></Grid>}<div className="mt-6 grid gap-5 md:grid-cols-2"><Area name="skills" title="Skill set"/><Area name="achievements" title="Achievements"/></div></Panel>}
        {step===4&&<Panel title="Contact details" note="Email and phone are required and checked for duplicate staff records in this school."><Grid><Field name="email" title="Email address" type="email" value={String(draft.email ?? "")} required/><Field name="phone" title="Phone number" type="tel" value={String(draft.phone ?? "")} placeholder="09096735531" maxLength={11} required/><Field name="website" title="Website" type="url"/><Area name="officeAddress" title="Residential / office address"/><Select name="socialPlatform" title="Social platform" optional options={["LinkedIn","Facebook","Instagram","X","YouTube"].map(x=>[x,x])}/><Field name="socialId" title="Profile link or handle"/><Area name="notes" title="Internal notes" wide/></Grid></Panel>}
        {step===5&&<Panel title="Photograph, signature and evidence" note="JPG, JPEG, PNG and PDF files use the secured document-storage workflow."><div className="grid gap-5 md:grid-cols-3"><FileField name="photo" title="Staff photograph"/><FileField name="signature" title="Staff signature"/><FileField name="qualificationDocument" title="Qualification document" document/></div>{showDocumentNotice&&<div role="status" className="mt-6 flex items-start justify-between gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><span>Review all tabs before creating the record. If a document upload fails, the staff profile remains available so the file can be added again from the staff detail page.</span><button type="button" onClick={() => setShowDocumentNotice(false)} aria-label="Dismiss document notice" className="grid size-7 shrink-0 place-items-center rounded-lg text-base text-amber-900 hover:bg-amber-100">×</button></div>}</Panel>}
        {error&&<div role="alert" className="mt-5 flex items-start justify-between gap-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-800"><span>{error}</span><button type="button" onClick={() => setError("")} aria-label="Dismiss error" className="grid size-6 shrink-0 place-items-center rounded-md text-red-700 hover:bg-red-100">×</button></div>}
      </div><footer className="flex items-center justify-between gap-3 border-t border-slate-200 bg-slate-50 px-5 py-4 sm:px-7"><button type="button" disabled={step===0||busy} onClick={()=>setStep(x=>x-1)} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-black disabled:opacity-40">Previous</button><div className="flex gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-black text-red-700 hover:bg-red-50">Cancel</button>{step<steps.length-1?<button type="button" onClick={event=>continueRegistration(event.currentTarget.form)} className="tenant-primary-bg rounded-xl px-5 py-2.5 text-sm font-black text-white">Continue</button>:<button disabled={busy} className="tenant-primary-bg rounded-xl px-5 py-2.5 text-sm font-black text-white disabled:opacity-50">{busy?"Creating staff record…":"Create staff record"}</button>}</div></footer></form>
    </div></div>}
  </div>;
}

function Panel({title,note,children}:{title:string;note:string;children:React.ReactNode}){return <section><h3 className="text-lg font-black text-slate-950">{title}</h3><p className="mb-6 mt-1 text-sm text-slate-500">{note}</p>{children}</section>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{children}</div>}
function Field({name,title,type="text",required=false,placeholder,value,readOnly,maxLength}:{name:string;title:string;type?:string;required?:boolean;placeholder?:string;value?:string;readOnly?:boolean;maxLength?:number}){return <label className={label}>{title}{required&&<span className="text-red-600"> *</span>}<input name={name} type={type} required={required} placeholder={placeholder} defaultValue={value} readOnly={readOnly} maxLength={maxLength} inputMode={type==="tel"?"numeric":undefined} onInput={type==="tel"?e=>{e.currentTarget.value=e.currentTarget.value.replace(/\D/g,"").slice(0,11)}:undefined} className={`${input} ${readOnly?"bg-slate-100 text-slate-500":""}`}/></label>}
function Select({name,title,options,optional=false,value,onChange,disabled=false,note}:{name:string;title:string;options:string[][];optional?:boolean;value?:string;onChange?:(v:string)=>void;disabled?:boolean;note?:string}){return <label className={label}>{title}{!optional&&<span className="text-red-600"> *</span>}<select name={name} required={!optional} value={value} onChange={onChange?e=>onChange(e.target.value):undefined} disabled={disabled} defaultValue={value===undefined?"":undefined} className={input}><option value="">{disabled?"Select a state first":"Select…"}</option>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select>{note&&<span className="mt-1 block font-normal text-slate-500">{note}</span>}</label>}
function Area({name,title,wide=false}:{name:string;title:string;wide?:boolean}){return <label className={`${label} ${wide?"md:col-span-2 xl:col-span-3":""}`}>{title}<textarea name={name} rows={3} className={input}/></label>}
function FileField({name,title,document=false}:{name:string;title:string;document?:boolean}){return <label className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5 text-sm font-black text-slate-800">{title}<span className="mt-1 block text-xs font-normal text-slate-500">{document?"PDF, JPG, JPEG or PNG":"JPG, JPEG or PNG"}, maximum 10 MB</span><input name={name} type="file" accept={document?"application/pdf,.jpg,.jpeg,.png,image/jpeg,image/png":".jpg,.jpeg,.png,image/jpeg,image/png"} className="mt-4 block w-full text-xs"/></label>}
function numberOrNull(value:FormDataEntryValue|null){const text=String(value??"");return text?Number(text):null}
async function problem(response:Response,fallback:string){try{const body=await response.json() as {detail?:string;message?:string;title?:string};return body.detail??body.message??body.title??fallback}catch{return fallback}}
