"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import type { ReactNode } from "react";
type Plan={id:string;code:string;name:string};
type Subscription={id:string;planCode:string;planName:string;startsAtUtc:string;endsAtUtc:string|null;graceEndsAtUtc:string|null;status:number};
const statuses=["Active","Grace period","Suspended","Expired","Cancelled"];
export function SubscriptionPage(){
 const [plans,setPlans]=useState<Plan[]>([]),[subscription,setSubscription]=useState<Subscription|null>(null),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const [plansResponse,currentResponse]=await Promise.all([fetch("/api/backend/plans",{cache:"no-store"}),fetch("/api/backend/subscriptions/current",{cache:"no-store"})]);if(!plansResponse.ok)throw new Error("Plans could not be loaded.");setPlans(await plansResponse.json() as Plan[]);if(currentResponse.ok)setSubscription(await currentResponse.json() as Subscription);else if(currentResponse.status===404)setSubscription(null);},[]);
 useEffect(()=>{void Promise.resolve().then(load).catch(value=>setError(value instanceof Error?value.message:"Subscription could not be loaded."));},[load]);
 async function request(path:string,body?:object){setBusy(true);setError("");setMessage("");const response=await fetch(`/api/backend/subscriptions/${path}`,{method:"POST",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});setBusy(false);if(!response.ok){setError("The subscription change could not be completed. Check its current state and supplied date.");return;}setMessage("Subscription lifecycle updated.");await load();}
 function futureDate(days:number){const date=new Date();date.setUTCDate(date.getUTCDate()+days);return date.toISOString();}
 return <main className="min-h-screen bg-[#f6f4ee] px-6 py-12"><div className="mx-auto max-w-4xl"><Link href="/portal" className="text-sm font-bold text-emerald-800">← Workspace</Link><h1 className="mt-6 text-4xl font-black">Subscription</h1><p className="mt-2 text-slate-600">Manage the school subscription and its access lifecycle.</p>{error&&<p role="alert" className="mt-6 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{message&&<p role="status" className="mt-6 rounded-xl bg-emerald-50 p-4 text-emerald-800">{message}</p>}{subscription?<section className="mt-8 rounded-3xl bg-white p-7 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wide text-emerald-800">{subscription.planCode}</p><h2 className="mt-1 text-2xl font-black">{subscription.planName}</h2></div><span className="rounded-full bg-slate-100 px-4 py-2 text-sm font-bold">{statuses[subscription.status]??"Unknown"}</span></div><dl className="mt-6 grid gap-4 sm:grid-cols-3"><DateValue label="Started" value={subscription.startsAtUtc}/><DateValue label="Current term ends" value={subscription.endsAtUtc}/><DateValue label="Grace ends" value={subscription.graceEndsAtUtc}/></dl><div className="mt-7 flex flex-wrap gap-3"><Action disabled={busy} onClick={()=>void request(`${subscription.id}/renew`,{endsAtUtc:futureDate(365)})}>Renew for one year</Action>{subscription.status===0&&<Action disabled={busy} secondary onClick={()=>void request(`${subscription.id}/grace-period`,{graceEndsAtUtc:futureDate(30)})}>Begin 30-day grace</Action>}{(subscription.status===0||subscription.status===1)&&<Action disabled={busy} danger onClick={()=>void request(`${subscription.id}/suspend`)}>Suspend</Action>}{(subscription.status===2||subscription.status===3)&&<Action disabled={busy} onClick={()=>void request(`${subscription.id}/reactivate`,{endsAtUtc:futureDate(365)})}>Reactivate</Action>}</div></section>:<div className="mt-8 grid gap-4 sm:grid-cols-2">{plans.map(plan=><article key={plan.id} className="rounded-3xl bg-white p-7 shadow-sm"><p className="text-sm font-bold uppercase tracking-wide text-emerald-800">{plan.code}</p><h2 className="mt-2 text-2xl font-black">{plan.name}</h2><p className="mt-3 text-slate-600">School administration, academics, staff, admissions, SIS and guardian management.</p><Action disabled={busy} onClick={()=>void request(plan.code)}>Activate plan</Action></article>)}</div>}</div></main>;
}
function DateValue({label,value}:{label:string;value:string|null}){return <div className="rounded-xl bg-slate-50 p-4"><dt className="text-xs font-bold uppercase text-slate-500">{label}</dt><dd className="mt-1">{value?new Date(value).toLocaleDateString():"Not set"}</dd></div>}
function Action({children,onClick,disabled,secondary,danger}:{children:ReactNode;onClick:()=>void;disabled:boolean;secondary?:boolean;danger?:boolean}){return <button disabled={disabled} onClick={onClick} className={`mt-3 rounded-xl px-4 py-3 font-bold disabled:opacity-50 ${danger?"border border-red-300 text-red-700":secondary?"border border-slate-300":"bg-[#12372a] text-white"}`}>{children}</button>}
